// Numerically validates the pure-CUDA port of
// include/mra/kernels/generate_op1d.h (generate_op1d_pure_cuda.h, at the
// repo root) against MADNESS's own GaussianConvolution1D::nonstandard() as
// ground truth, AND (always) dumps the same MADNESS reference data to a
// self-contained C++ header for standalone use (generate_op1d_compare_madness.cu).
//
// This single source builds two ways (see src/tests/CMakeLists.txt):
//  - mra-generate-op1d-reference-dump (host-only, plain .cc): constructs the
//    MADNESS term, writes generate_op1d_reference_data.h, and exits -- no
//    GPU or CUDA toolchain needed.
//  - mra-generate-op1d-reference-dump-device-cuda-parsec (wrapped via
//    mra_generate_gpu_wrappers into a .cu, compiled by nvcc): does the same,
//    PLUS -- in the same process, no file round-trip needed -- launches
//    generate_op1d_pure_cuda.h's kernel on the same inputs and compares
//    directly against MADNESS's nonstandard() output, printing a per-case
//    PASS/FAIL and exiting nonzero on any failure. Deliberately does NOT
//    link mra::cuda/MADmra (unlike this directory's other -device-cuda-parsec
//    targets): generate_op1d_pure_cuda.h has no TTG/mra framework
//    dependency, and pulling those in would reintroduce the same
//    MADNESS+TTG+PARSEC single-translation-unit compile weight that made
//    generate_op1d_pure_cuda.h a *pure* CUDA port worth having in the first
//    place (see that header's own comment).
//
// Both construct a single GaussianConvolution1D term directly -- the same
// object type GaussianConvolutionOperator::extract_gaussian_terms_for_device()
// (mra/misc/conv_mad.h) downcasts each real operator's separated-expansion
// terms to. Bypassing the full SeparatedConvolution/GFit machinery keeps
// this simple while exercising exactly the same per-term math the device
// generator actually processes.
//
// Usage: mra-generate-op1d-reference-dump[-device-cuda-parsec] [output_path]
//   (default output_path: generate_op1d_reference_data.h, in the current directory)

#include <ttg.h>
#include "mra/mra.h"

#include <madness/mra/convolution1d.h>
#include <madness/mra/kernelrange.h>

#ifdef __CUDACC__
#include "generate_op1d_pure_cuda.h" // repo root; see this target's target_include_directories
#endif

#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <string>
#include <vector>

namespace {

struct CaseSpec {
  int n;
  long long lx;
};

struct CaseData {
  int n;
  long long lx;
  std::vector<double> R; // (2K)x(2K), row-major
  std::vector<double> S; // KxK, row-major
  double Rnorm, Snorm, Rnormf, Snormf, NSnormf;
  bool empty;
};

void dump_array(std::ostream& out, const char* name, const std::vector<double>& data) {
  out << "static const double " << name << "[" << data.size() << "] = {\n";
  for (size_t i = 0; i < data.size(); ++i) {
    out << data[i];
    if (i + 1 < data.size()) out << ",";
    out << ((i + 1) % 6 == 0 ? "\n" : " ");
  }
  out << "\n};\n\n";
}

void write_header(const std::string& out_path, int K, int npt, double coeff, double expnt, int natlev, int m,
                   const std::vector<double>& quad_x, const std::vector<double>& quad_w,
                   const std::vector<double>& c, const std::vector<double>& hgT,
                   const std::vector<double>& hgT2k, const std::vector<CaseData>& cases) {
  std::ofstream out(out_path);
  if (!out) {
    std::fprintf(stderr, "FATAL: cannot open %s for writing\n", out_path.c_str());
    return;
  }
  out << std::setprecision(17);
  out << "// AUTO-GENERATED by src/tests/generate_op1d_reference_dump.cc -- do not hand-edit.\n"
      << "// Real MADNESS GaussianConvolution1D<double> reference data: K=" << K << " coeff=" << coeff
      << " expnt=" << expnt << " m=" << m << " natlev=" << natlev << " (single term, non-periodic).\n"
      << "// See generate_op1d_compare_madness.cu for how this is used.\n\n"
      << "#ifndef GENERATE_OP1D_REFERENCE_DATA_H\n#define GENERATE_OP1D_REFERENCE_DATA_H\n\n"
      << "static const int REF_K = " << K << ";\n"
      << "static const int REF_NPT = " << npt << ";\n"
      << "static const double REF_COEFF = " << coeff << ";\n"
      << "static const double REF_EXPNT = " << expnt << ";\n"
      << "static const int REF_NATLEV = " << natlev << ";\n"
      << "static const int REF_M = " << m << ";\n\n";

  dump_array(out, "REF_QUAD_X", quad_x);
  dump_array(out, "REF_QUAD_W", quad_w);
  dump_array(out, "REF_C", c);
  dump_array(out, "REF_HGT", hgT);
  dump_array(out, "REF_HGT2K", hgT2k);

  const long long r_size = (long long)(2 * K) * (2 * K);
  const long long s_size = (long long)K * K;

  out << "struct RefCase {\n"
      << "  int n; long long lx;\n"
      << "  double R[" << r_size << "];\n"
      << "  double S[" << s_size << "];\n"
      << "  double Rnorm, Snorm, Rnormf, Snormf, NSnormf;\n"
      << "  bool empty;\n"
      << "};\n\n"
      << "static const int REF_NUM_CASES = " << cases.size() << ";\n"
      << "static const RefCase REF_CASES[REF_NUM_CASES] = {\n";
  for (const auto& cd : cases) {
    out << "  { " << cd.n << ", " << cd.lx << "LL,\n    {";
    for (long long i = 0; i < r_size; ++i) {
      out << cd.R[i];
      if (i + 1 < r_size) out << ",";
      out << ((i + 1) % 6 == 0 ? "\n     " : " ");
    }
    out << "},\n    {";
    for (long long i = 0; i < s_size; ++i) {
      out << cd.S[i];
      if (i + 1 < s_size) out << ",";
      out << ((i + 1) % 6 == 0 ? "\n     " : " ");
    }
    out << "},\n    " << cd.Rnorm << ", " << cd.Snorm << ", " << cd.Rnormf << ", " << cd.Snormf << ", "
        << cd.NSnormf << ",\n"
        << "    " << (cd.empty ? "true" : "false") << "\n  },\n";
  }
  out << "};\n\n#endif // GENERATE_OP1D_REFERENCE_DATA_H\n";
}

#ifdef __CUDACC__
// Absolute+relative tolerance: |a-b| <= atol + rtol*max(|a|,|b|).
bool close(double a, double b, double atol, double rtol) {
  return std::fabs(a - b) <= atol + rtol * std::max(std::fabs(a), std::fabs(b));
}

// Runs generate_op1d_pure_cuda.h's kernel on the same inputs and compares
// against MADNESS's nonstandard() output (`cases`). Returns true iff every
// case passed. See generate_op1d_compare_madness.cu's header comment for
// why Rnorm/Snorm are checked as a bound, not equality.
bool run_comparison(int K, int npt, double coeff, double expnt, int natlev, int m,
                     const std::vector<double>& quad_x, const std::vector<double>& quad_w,
                     const std::vector<double>& c, const std::vector<double>& hgT,
                     const std::vector<double>& hgT2k, const std::vector<CaseData>& cases) {
  const double atol = 1e-9;
  const double rtol = 1e-8;

  double *quad_x_dev, *quad_w_dev, *c_dev, *hgT_dev, *hgT2k_dev;
  check_cuda(cudaMalloc(&quad_x_dev, sizeof(double) * quad_x.size()), "cudaMalloc quad_x");
  check_cuda(cudaMalloc(&quad_w_dev, sizeof(double) * quad_w.size()), "cudaMalloc quad_w");
  check_cuda(cudaMalloc(&c_dev, sizeof(double) * c.size()), "cudaMalloc c");
  check_cuda(cudaMalloc(&hgT_dev, sizeof(double) * hgT.size()), "cudaMalloc hgT");
  check_cuda(cudaMalloc(&hgT2k_dev, sizeof(double) * hgT2k.size()), "cudaMalloc hgT2k");
  check_cuda(cudaMemcpy(quad_x_dev, quad_x.data(), sizeof(double) * quad_x.size(), cudaMemcpyHostToDevice),
             "H2D quad_x");
  check_cuda(cudaMemcpy(quad_w_dev, quad_w.data(), sizeof(double) * quad_w.size(), cudaMemcpyHostToDevice),
             "H2D quad_w");
  check_cuda(cudaMemcpy(c_dev, c.data(), sizeof(double) * c.size(), cudaMemcpyHostToDevice), "H2D c");
  check_cuda(cudaMemcpy(hgT_dev, hgT.data(), sizeof(double) * hgT.size(), cudaMemcpyHostToDevice), "H2D hgT");
  check_cuda(cudaMemcpy(hgT2k_dev, hgT2k.data(), sizeof(double) * hgT2k.size(), cudaMemcpyHostToDevice),
             "H2D hgT2k");

  const int n_items = (int)cases.size();
  const long long r_size = (long long)(2 * K) * (2 * K);
  const long long s_size = (long long)K * K;

  double *R_dev, *S_dev, *norms_dev;
  check_cuda(cudaMalloc(&R_dev, sizeof(double) * n_items * r_size), "cudaMalloc R");
  check_cuda(cudaMalloc(&S_dev, sizeof(double) * n_items * s_size), "cudaMalloc S");
  check_cuda(cudaMalloc(&norms_dev, sizeof(double) * n_items * 5), "cudaMalloc norms");

  std::vector<GenerateOp1DItem> items_host(n_items);
  for (int i = 0; i < n_items; ++i) {
    items_host[i].params = GaussianTermParams{/*coeff=*/coeff, /*fac=*/1.0, /*expnt=*/expnt,
                                               /*natlev=*/(Level)natlev, /*m=*/m};
    items_host[i].n = cases[i].n;
    items_host[i].lx = cases[i].lx;
    items_host[i].R_dst = R_dev + (size_t)i * r_size;
    items_host[i].S_dst = S_dev + (size_t)i * s_size;
    items_host[i].norms_dst = norms_dev + (size_t)i * 5;
  }
  GenerateOp1DItem* items_dev;
  check_cuda(cudaMalloc(&items_dev, sizeof(GenerateOp1DItem) * n_items), "cudaMalloc items");
  check_cuda(
      cudaMemcpy(items_dev, items_host.data(), sizeof(GenerateOp1DItem) * n_items, cudaMemcpyHostToDevice),
      "H2D items");

  double* workspace_dev;
  check_cuda(cudaMalloc(&workspace_dev, sizeof(double) * workspace_size(K) * n_items), "cudaMalloc workspace");

  submit_generate_op1d_kernel(items_dev, n_items, K, c_dev, hgT_dev, hgT2k_dev, quad_x_dev, quad_w_dev, npt,
                               workspace_dev, /*stream=*/0);
  check_cuda(cudaDeviceSynchronize(), "cudaDeviceSynchronize");

  std::vector<double> R_out(n_items * r_size), S_out(n_items * s_size), norms_out(n_items * 5);
  check_cuda(cudaMemcpy(R_out.data(), R_dev, sizeof(double) * R_out.size(), cudaMemcpyDeviceToHost), "D2H R");
  check_cuda(cudaMemcpy(S_out.data(), S_dev, sizeof(double) * S_out.size(), cudaMemcpyDeviceToHost), "D2H S");
  check_cuda(cudaMemcpy(norms_out.data(), norms_dev, sizeof(double) * norms_out.size(), cudaMemcpyDeviceToHost),
             "D2H norms");

  int num_pass = 0;
  for (int i = 0; i < n_items; ++i) {
    bool pass = true;
    double max_r_err = 0.0, max_s_err = 0.0;
    const double* R = &R_out[(size_t)i * r_size];
    const double* S = &S_out[(size_t)i * s_size];
    const double* norms = &norms_out[(size_t)i * 5];
    const CaseData& ref = cases[i];

    for (long long k = 0; k < r_size; ++k) {
      max_r_err = std::max(max_r_err, std::fabs(R[k] - ref.R[k]));
      if (!close(R[k], ref.R[k], atol, rtol)) pass = false;
    }
    for (long long k = 0; k < s_size; ++k) {
      max_s_err = std::max(max_s_err, std::fabs(S[k] - ref.S[k]));
      if (!close(S[k], ref.S[k], atol, rtol)) pass = false;
    }
    double rnormf_err = std::fabs(norms[2] - ref.Rnormf);
    double snormf_err = std::fabs(norms[3] - ref.Snormf);
    double nsnormf_err = std::fabs(norms[4] - ref.NSnormf);
    if (!close(norms[2], ref.Rnormf, atol, rtol)) pass = false;
    if (!close(norms[3], ref.Snormf, atol, rtol)) pass = false;
    if (!close(norms[4], ref.NSnormf, atol, rtol)) pass = false;

    // Rnorm/Snorm: this kernel's sqrt(dim)*Frobenius must be a conservative
    // upper bound on MADNESS's exact SVD nuclear norm -- see this file's
    // header comment. Never expect equality.
    bool rnorm_bound_ok = (norms[0] >= ref.Rnorm - atol);
    bool snorm_bound_ok = (norms[1] >= ref.Snorm - atol);
    if (!rnorm_bound_ok || !snorm_bound_ok) pass = false;

    std::printf(
        "case %d (n=%d, lx=%lld, %s): %s  max|dR|=%.3g max|dS|=%.3g dRnormf=%.3g dSnormf=%.3g dNSnormf=%.3g  "
        "Rnorm(mine)=%.6g >= Rnorm(madness)=%.6g? %s  Snorm(mine)=%.6g >= Snorm(madness)=%.6g? %s\n",
        i, ref.n, ref.lx, ref.empty ? "issmall" : "regular", pass ? "PASS" : "FAIL", max_r_err, max_s_err,
        rnormf_err, snormf_err, nsnormf_err, norms[0], ref.Rnorm, rnorm_bound_ok ? "yes" : "NO", norms[1],
        ref.Snorm, snorm_bound_ok ? "yes" : "NO");

    if (pass) ++num_pass;
  }

  cudaFree(quad_x_dev);
  cudaFree(quad_w_dev);
  cudaFree(c_dev);
  cudaFree(hgT_dev);
  cudaFree(hgT2k_dev);
  cudaFree(R_dev);
  cudaFree(S_dev);
  cudaFree(norms_dev);
  cudaFree(items_dev);
  cudaFree(workspace_dev);

  std::printf("\n%d/%d cases passed (atol=%.1e, rtol=%.1e)\n", num_pass, n_items, atol, rtol);
  return num_pass == n_items;
}
#endif // __CUDACC__

} // namespace

int main(int argc, char** argv) {
  const int K = 6;
  const double coeff = 1.0;
  const double expnt = 10.0;
  std::string out_path = (argc > 1) ? argv[1] : "generate_op1d_reference_data.h";

  // autoc()/two_scale_hg() (called by Convolution1D's base ctor) need their
  // coefficient tables loaded first, which mra::initialize() triggers as a
  // side effect (without it: "autoc: invalid k 6"). Deliberately skipping
  // the matching mra::finalize() below -- see main()'s tail comment.
  mra::initialize(argc, argv, -1);

  madness::GaussianConvolution1D<double> term(K, coeff, expnt, /*m=*/0, madness::LatticeRange());
  const int npt = term.npt;
  const int natlev = (int)term.natlev;
  const int m = term.m;

  std::vector<double> quad_x(term.quad_x.ptr(), term.quad_x.ptr() + npt);
  std::vector<double> quad_w(term.quad_w.ptr(), term.quad_w.ptr() + npt);
  std::vector<double> c(term.c.ptr(), term.c.ptr() + (long long)K * K * 4 * K);
  std::vector<double> hgT(term.hgT.ptr(), term.hgT.ptr() + (long long)2 * K * 2 * K);
  std::vector<double> hgT2k(term.hgT2k.ptr(), term.hgT2k.ptr() + (long long)4 * K * 4 * K);

  const std::vector<CaseSpec> case_specs = {{0, 0}, {0, 1}, {1, 0}, {1, 1}, {2, 0}, {2, 1}, {3, 0}, {3, 2}};
  const long long r_size = (long long)(2 * K) * (2 * K);
  const long long s_size = (long long)K * K;

  std::vector<CaseData> cases;
  cases.reserve(case_specs.size());
  int num_empty = 0;
  for (const auto& spec : case_specs) {
    const madness::ConvolutionData1D<double>* cd = term.nonstandard(spec.n, spec.lx);
    CaseData data;
    data.n = spec.n;
    data.lx = spec.lx;
    data.empty = (cd->R.size() == 0 && cd->T.size() == 0);
    data.R.assign(r_size, 0.0);
    data.S.assign(s_size, 0.0);
    if (!data.empty) {
      std::copy(cd->R.ptr(), cd->R.ptr() + r_size, data.R.begin());
      std::copy(cd->T.ptr(), cd->T.ptr() + s_size, data.S.begin());
    }
    data.Rnorm = data.empty ? 0.0 : cd->Rnorm;
    data.Snorm = data.empty ? 0.0 : cd->Tnorm;
    data.Rnormf = data.empty ? 0.0 : cd->Rnormf;
    data.Snormf = data.empty ? 0.0 : cd->Tnormf;
    data.NSnormf = data.empty ? 0.0 : cd->NSnormf;
    if (data.empty) ++num_empty;
    cases.push_back(std::move(data));
  }

  write_header(out_path, K, npt, coeff, expnt, natlev, m, quad_x, quad_w, c, hgT, hgT2k, cases);
  std::printf("Wrote %s (%zu cases, %d empty/issmall)\n", out_path.c_str(), case_specs.size(), num_empty);

  bool ok = true;
#ifdef __CUDACC__
  std::printf("\nRunning generate_op1d_pure_cuda.h's kernel and comparing against MADNESS...\n");
  ok = run_comparison(K, npt, coeff, expnt, natlev, m, quad_x, quad_w, c, hgT, hgT2k, cases);
#else
  std::printf("(built without CUDA -- comparison skipped; build "
              "mra-generate-op1d-reference-dump-device-cuda-parsec for the full numerical check)\n");
#endif

  // Deliberately not calling mra::finalize(): PaRSEC's world-teardown path
  // (parsec_termdet_fourcounter_unmonitor_taskpool) aborts on this machine
  // for reasons unrelated to anything above -- all real work is already
  // done by this point, so just let the OS reclaim the process instead of
  // chasing an unrelated shutdown bug in a one-shot test/dump tool.
  // _Exit() skips the usual stdio flush, so do it explicitly first.
  std::fflush(nullptr);
  std::_Exit(ok ? 0 : 1);
}
