#ifndef MRA_KERNELS_GENERATE_OP1D_H
#define MRA_KERNELS_GENERATE_OP1D_H

/**
 * On-device generation of the per-(level, dimension, translation) 1D
 * transition-matrix tensors (R, S, and their norms) used by the convolution
 * operator (see mra/misc/conv_mad.h). This replaces calling into MADNESS's
 * Convolution1D::nonstandard() on the CPU -- the actual bottleneck that
 * motivated this file: that CPU work sat on the critical path of a device
 * task and could not keep the GPU busy.
 *
 * The math is ported from mra::Convolution in mra/misc/convolutiondata.h
 * (a from-scratch, MADNESS-free CPU reference implementing the same
 * quadrature-projection / autocorrelation / two-scale-filter algorithm),
 * generalized to take the per-term Gaussian parameters (coeff, expnt,
 * natlev) and the shared autocorrelation/two-scale-filter tensors as
 * arguments instead of owning them, so the *many* separated-expansion terms
 * of a real operator (extracted once, on the host, from MADNESS's
 * GaussianConvolution1D -- see conv_mad.h) can all be generated by one
 * kernel launch.
 *
 * Known limitations of this first pass (see mra/misc/conv_mad.h for the
 * fuller rationale):
 *  - Only plain (m==0) Gaussian terms are supported; derivative operators
 *    (m==1,2) are not generated here.
 *  - Rnorm/Snorm are NOT MADNESS's exact SVD-based nuclear norm (that would
 *    require an on-device SVD). Instead we use the standard bound
 *    ||A||_nuclear <= sqrt(n) * ||A||_F, i.e. Rnorm_approx = sqrt(2K)*Rnormf,
 *    Snorm_approx = sqrt(K)*Snormf. This can only make the application
 *    kernel's screening MORE conservative than MADNESS's tighter bound
 *    (never wrongly skips a term that should contribute) -- a performance
 *    cost, not a correctness one.
 */

#include "mra/misc/platform.h"
#include "mra/misc/types.h"
#include "mra/misc/maxk.h"
#include "mra/tensor/tensorview.h"
#include "mra/ops/functions.h" // for mra::detail::normf -- cooperative block-wide reduction, reused below

/**
 * Upper bound on get_rnlp_device's tree depth (natlev - n). MADNESS itself
 * never uses tree levels beyond MAX_LEVEL == 31 (see the KeyPair::hash()
 * comment in mra/tasks/convolution.h), so no legitimate (n, natlev) pair can
 * need to descend further than that -- this is a real, meaningful bound, not
 * an arbitrary guess. Overridable like MRA_MAX_K for the same reason.
 */
#ifndef MRA_OP1D_MAX_RECURSION_DEPTH
#define MRA_OP1D_MAX_RECURSION_DEPTH 32
#endif // MRA_OP1D_MAX_RECURSION_DEPTH

namespace mra {

  /**
   * Per-term Gaussian parameters, extracted ONCE (at GaussianConvolutionOperator
   * construction, on the host) from MADNESS's GaussianConvolution1D -- see
   * conv_mad.h's extraction code. Tiny POD, travels by value per work item
   * (the same way tol/at already travel per-member in ConvolutionBatchArg,
   * see mra/kernels/convolution.h) rather than through a Tensor/Buffer.
   */
  template <typename T>
  struct GaussianTermParams {
    T coeff = T(0);
    T fac = T(0);
    T expnt = T(0);
    Level natlev = 0;
    int m = 0; // derivative order; only m==0 is generated on device (see above)
  };

  /**
   * One (term, dimension, level, translation) unit of work: generate R/S and
   * their norms for this single 1D transition matrix, writing directly into
   * the caller-provided destination views (slices of the real
   * ConvolutionData1D<T>::R/S/norms1d tensors -- see conv_mad.h). Trivially
   * copyable (plain scalars + TensorView descriptors), so a std::vector of
   * these can be uploaded with one H2D copy, same as any other batch-arg
   * struct in this codebase.
   */
  template <typename T>
  struct GenerateOp1DItem {
    GaussianTermParams<T> params;
    Level n = 0;
    Translation lx = 0;
    DenseTensorView<T, 2> R_dst;      // 2K x 2K
    DenseTensorView<T, 2> S_dst;      // K x K
    DenseTensorView<T, 1> norms_dst;  // length 5: Rnorm,Snorm,Rnormf,Snormf,NSnormf
                                      // (matches the first 5 values of conv_mad.h's NormId)
  };

  namespace detail {

    /// Ported from mra::Convolution::issmall (misc/convolutiondata.h).
    template <typename T>
    DEVSCOPE bool op1d_issmall(T expnt, Level n, Translation lx) {
      T beta = expnt * exp2(T(-2) * T(n));
      Translation l;
      if (lx > 0) l = lx - 1;
      else if (lx < 0) l = -lx - 1;
      else l = 0;
      return beta * T(l) * T(l) > T(49.0);
    }

    /// Ported from legendre_scaling_functions (src/gl.cc), which is host-only
    /// (backed by a host-resident normalization table) -- this is the
    /// device-portable equivalent, computed directly instead of from a table
    /// since the recurrence coefficients (n/(n+1), sqrt(2n+1)) are cheap to
    /// evaluate inline. p must have room for k elements.
    template <typename T>
    DEVSCOPE void legendre_scaling_device(T x, size_type k, T* p) {
      T z = T(2) * x - T(1);
      p[0] = T(1);
      if (k > 1) p[1] = z;
      if (thread_id() > 0) {
        for (size_type n = thread_id(); n + 1 < k; n += block_size()) {
          T nn1 = T(n) / T(n + 1);
          p[n + 1] = (z * p[n] - p[n - 1]) * nn1 + z * p[n];
        }
      }
      for (size_type n = thread_id(); n < k; n += block_size()) {
        p[n] *= sqrt(T(2) * T(n) + T(1));
      }
    }

    /**
     * Per-item scratch layout for the cooperative generator below. Every
     * region is block-wide -- written and read by every thread in the
     * block, via caller-allocated GLOBAL memory (one region per work item,
     * sized by op1d_workspace_size(K) and indexed by the item's position in
     * the batch -- see submit_generate_op1d_kernel). Deliberately not CUDA
     * __shared__ memory: that would need either compile-time sizing (K is a
     * runtime value here) or an extern-shared/pointer-carving scheme, plus
     * it runs into the team-lead-only-SHARED-rebind-before-SYNCTHREADS nvcc
     * miscompile pitfall already flagged elsewhere in this codebase (see
     * e.g. compress_process_one_leader's comment in kernels/compress.h).
     * Plain per-item global memory sidesteps both at a modest bandwidth
     * cost -- acceptable here since generation is not the hot loop this
     * whole effort is trying to keep off (that's MADNESS's CPU-side
     * nonstandard() call; see this file's header comment).
     */
    struct Op1DWorkspaceOffsets {
      size_type leftbuf;     // [MRA_OP1D_MAX_RECURSION_DEPTH][2K]
      size_type retbuf;      // [2K]
      size_type combine_out; // [2K] -- see get_rnlp_device's WAIT_RIGHT comment for why this must
                              // be distinct from retbuf/leftbuf, not an in-place combine target
      size_type rnlp1;       // [2K]
      size_type rnlp2;       // [2K]
      size_type Rvec;        // [4K]
      size_type rm;          // [K*K]
      size_type r0;          // [K*K]
      size_type rp;          // [K*K]
      size_type tmp;         // [2K*2K]
      size_type t0;          // [2K*2K]
      size_type rmat;        // [2K*2K]
      size_type smat;        // [K*K]
      size_type ns_scratch;  // [2K*2K]
      size_type total;

      Op1DWorkspaceOffsets(auto K)
      {
        size_type p = 0;
        leftbuf = p; p += MRA_OP1D_MAX_RECURSION_DEPTH * 2 * K;
        retbuf = p; p += 2 * K;
        combine_out = p; p += 2 * K;
        rnlp1 = p; p += 2 * K;
        rnlp2 = p; p += 2 * K;
        Rvec = p; p += 4 * K;
        rm = p; p += K * K;
        r0 = p; p += K * K;
        rp = p; p += K * K;
        tmp = p; p += 2 * K * 2 * K;
        t0 = p; p += 2 * K * 2 * K;
        rmat = p; p += 2 * K * 2 * K;
        smat = p; p += K * K;
        ns_scratch = p; p += 2 * K * 2 * K;
        total = p;
      }
    };

    SCOPE Op1DWorkspaceOffsets op1d_workspace_offsets(size_type K) {
      Op1DWorkspaceOffsets o{K};
      return o;
    }

    /// Ported from mra::Convolution::make_rnlp (misc/convolutiondata.h): the
    /// leaf (base-case) quadrature projection of the Gaussian onto
    /// double-order polynomials. `out` is block-wide (shared) scratch with
    /// room for 2*K elements.
    ///
    /// Cooperative, but not by distributing the (box, quadrature-point)
    /// summation itself: every thread redundantly walks the full loop (all
    /// its inputs -- coeff/expnt/n/lx -- are scalars identical across the
    /// block, so this is cheap and, critically, avoids needing a reduction
    /// or atomics over `out`) into a private accumulator, then each thread
    /// publishes only the output coefficients it owns (thread_id()-strided)
    /// to the shared `out` -- no two threads ever write the same index.
    template <typename T>
    DEVSCOPE void make_rnlp_leaf(T coeff, T expnt, size_type K, size_type npt,
                                  const T* quad_x, const T* quad_w,
                                  Level n, Translation lx, T* out) {
      Translation lkeep = lx;
      Translation lxx = (lx < 0) ? (-lx - 1) : lx;
      T scaledcoeff = coeff * exp2(T(-0.5) * T(n));
      T beta = expnt * exp2(T(-2) * T(n));
      T h = T(1) / sqrt(beta);
      size_type nbox = size_type(T(1) / h);
      if (nbox < 1) nbox = 1;
      h = T(1) / T(nbox);
      T sch = fabs(scaledcoeff * h);
      T argmax = fabs(log(T(1e-22) / sch));

      SHARED T acc[2 * MRA_MAX_K_SIZET];
      SHARED T phix[2 * MRA_MAX_K_SIZET];
      for (size_type p = thread_id(); p < 2 * K; p += block_size()) acc[p] = T(0);
      for (size_type box = 0; box < nbox; ++box) {
        T xlo = T(box) * h + T(lxx);
        if (beta * xlo * xlo > argmax) break; // same decision on every thread -- no divergence
        for (size_type i = 0; i < (size_type)npt; ++i) {
          T xx = xlo + h * quad_x[i];
          T ee = scaledcoeff * exp(-beta * xx * xx) * quad_w[i] * h;
          legendre_scaling_device(xx - T(lxx), 2 * K, phix);
          for (size_type p = thread_id(); p < 2 * K; p += block_size()) acc[p] += ee * phix[p];
        }
      }
      if (lkeep < 0) {
        for (size_type p = 1; p < 2 * K; p += 2) acc[p] = -acc[p];
      }
      for (size_type p = thread_id(); p < 2 * K; p += block_size()) out[p] = acc[p];
      SYNCTHREADS();
    }

    /**
     * Ported from mra::Convolution::get_rnlp (misc/convolutiondata.h):
     * projects onto a finer level (via the order-2K two-scale filter hgT2k,
     * exactly MADNESS's own Convolution1D::hgT2k -- see conv_mad.h's
     * extraction code) until issmall() cuts it off or the Gaussian's natural
     * level is reached, then falls back to the leaf quadrature sum. On
     * return, `retbuf` (block-wide scratch, 2*K elements) holds the answer.
     *
     * The combine step's contraction (out[j] = sum_k tmp[k]*hgT2k(k,j)) is
     * mra::transform's convention for a 1D input, verified directly against
     * mTxmq's documented contract (mra/ops/mxm.h: c(i,j)=sum_k a(k,i)*b(k,j),
     * here dimi==1) rather than re-derived from the generic (NDIM-tensor)
     * mra::transform helper -- see this file's header comment.
     *
     * Implemented as an explicit-stack post-order traversal rather than true
     * recursion (the conceptual algorithm is still exactly the recursive one
     * -- two child calls at (n+1, 2*lx) / (n+1, 2*lx+1), combined via
     * hgT2k). A real recursive __device__ function makes per-thread local-
     * memory/stack sizing unpredictable for the compiler (and risks a
     * runtime stack overflow across many concurrent threads if actual depth
     * exceeds whatever nvcc assumed); this version's control-flow state is a
     * fixed, statically-sized, per-thread-PRIVATE array instead --
     * MRA_OP1D_MAX_RECURSION_DEPTH frames, each just a small (n, lx, state)
     * triple. Kept private (redundantly identical on every thread, since it
     * depends only on scalar inputs shared by the whole block) rather than
     * promoted to the block-wide `leftbuf`/`retbuf`/`combine_out` scratch,
     * which hold the actual numerical results and are the only things that
     * need synchronization.
     *
     * Each frame starts ENTER (not yet processed): issmall() prunes it to a
     * zero leaf immediately; n>=natlev makes it a quadrature leaf; otherwise
     * it's an internal node -- push the left child (frame state becomes
     * WAIT_LEFT) and let the loop resolve it (however deep that takes,
     * within the same fixed stack). When a WAIT_LEFT frame is revisited (only
     * possible immediately after its child popped, so retbuf reliably holds
     * that child's result, synchronized), stash it into leftbuf[top] and
     * push the right child (state becomes WAIT_RIGHT). When a WAIT_RIGHT
     * frame is revisited, retbuf holds the right child's result; combine it
     * with leftbuf[top] via hgT2k into combine_out (a buffer distinct from
     * both inputs -- every thread's output index reads the FULL 4K
     * concatenated vector, so overwriting either input in place while other
     * threads may still be reading it would race), then copy combine_out
     * back into retbuf for the parent to consume. When the stack empties,
     * retbuf holds the original (n0, lx0) query's answer.
     */
    template <typename T, concepts::TensorView<2> ViewHgT2k>
    DEVSCOPE void get_rnlp_device(const GaussianTermParams<T>& p, size_type K, size_type npt,
                                   const T* quad_x, const T* quad_w,
                                   const ViewHgT2k& hgT2k,
                                   Level n0, Translation lx0,
                                   T* leftbuf, T* retbuf, T* combine_out) {
      enum FrameState : unsigned char { ENTER, WAIT_LEFT, WAIT_RIGHT };
      struct Frame {
        Level n;
        Translation lx;
        FrameState state;
      };

      SHARED Frame stack[MRA_OP1D_MAX_RECURSION_DEPTH]; // per-thread private; see header comment
      size_type sp = 0;
      if (is_team_lead()) {
        stack[sp].n = n0;
        stack[sp].lx = lx0;
        stack[sp].state = ENTER;
      }
      SYNCTHREADS();
      ++sp;

      while (sp > 0) {
        const size_type top = sp - 1;
        Frame& f = stack[top];

        if (f.state == ENTER) {
          if (op1d_issmall(p.expnt, f.n, f.lx)) {
            for (size_type i = thread_id(); i < 2 * K; i += block_size()) retbuf[i] = T(0);
            SYNCTHREADS();
            --sp;
            continue;
          }
          if (f.n < p.natlev) {
            if (is_team_lead()) {
              f.state = WAIT_LEFT;
            }
            SYNCTHREADS();
            if (sp >= MRA_OP1D_MAX_RECURSION_DEPTH) {
              if (is_team_lead()) {
                THROWF("get_rnlp_device: recursion depth exceeded MRA_OP1D_MAX_RECURSION_DEPTH (%d)\n",
                       MRA_OP1D_MAX_RECURSION_DEPTH);
              }
              return;
            }
            if (is_team_lead()) {
              stack[sp].n = f.n + 1;
              stack[sp].lx = 2 * f.lx;
              stack[sp].state = ENTER;
            }
            SYNCTHREADS();
            ++sp;
            continue;
          }
          make_rnlp_leaf(p.coeff, p.expnt, K, npt, quad_x, quad_w, f.n, f.lx, retbuf); // already synced internally
          --sp;
          continue;
        }

        if (f.state == WAIT_LEFT) {
          for (size_type i = thread_id(); i < 2 * K; i += block_size())
            leftbuf[top * 2 * K + i] = retbuf[i];
          if (is_team_lead()) {
            f.state = WAIT_RIGHT;
          }
          SYNCTHREADS();
          if (sp >= MRA_OP1D_MAX_RECURSION_DEPTH) {
            if (is_team_lead()) {
              THROWF("get_rnlp_device: recursion depth exceeded MRA_OP1D_MAX_RECURSION_DEPTH (%d)\n",
                     MRA_OP1D_MAX_RECURSION_DEPTH);
            }
            return;
          }
          if (is_team_lead()) {
            stack[sp].n = f.n + 1;
            stack[sp].lx = 2 * f.lx + 1;
            stack[sp].state = ENTER;
          }
          SYNCTHREADS();
          ++sp;
          continue;
        }

        // f.state == WAIT_RIGHT: retbuf holds the right child's result,
        // leftbuf[top] the (already-computed) left child's.
        {
          for (size_type j = thread_id(); j < 2 * K; j += block_size()) {
            T acc = T(0);
            for (size_type k = 0; k < 2 * K; ++k) acc += leftbuf[top * 2 * K + k] * hgT2k(k, j);
            for (size_type k = 0; k < 2 * K; ++k) acc += retbuf[k] * hgT2k(2 * K + k, j);
            combine_out[j] = acc;
          }
          SYNCTHREADS();
          for (size_type j = thread_id(); j < 2 * K; j += block_size()) retbuf[j] = combine_out[j];
          SYNCTHREADS();
          --sp;
        }
      }
      // retbuf now holds the (n0, lx0) query's answer -- caller reads it directly.
    }

    /**
     * Ported from mra::Convolution::make_rnlij (misc/convolutiondata.h):
     * projects the Gaussian onto the KxK "rnlij" block via an inner product
     * against the autocorrelation tensor c (K x K x 4K -- MADNESS's own
     * Convolution1D::c, see conv_mad.h's extraction code). `out` (block-wide
     * scratch, K*K elements, row-major out[qi*K+qj]) holds the result on
     * return.
     *
     * The contraction (out(qi,qj) = sum_k c(qi,qj,k)*Rvec[k]) is verified
     * directly against mra::detail::inner's documented case
     * "k0==(left.ndim()-1) && k1==0 -> c[i,j]=a[i,k]*b[k,j]" (mra/ops/inner.h)
     * with the K*K output flattened back to (qi,qj) -- see this file's
     * header comment.
     *
     * leftbuf/retbuf/combine_out are get_rnlp_device's own scratch (passed
     * through); rnlp1/rnlp2/Rvec are this function's own block-wide scratch.
     */
    template <typename T, concepts::TensorView<2> ViewHgT2k, concepts::TensorView<3> ViewC>
    DEVSCOPE void make_rnlij_device(const GaussianTermParams<T>& p, size_type K, size_type npt,
                                     const T* quad_x, const T* quad_w,
                                     const ViewHgT2k& hgT2k,
                                     const ViewC& cten,
                                     Level n, Translation lx,
                                     T* leftbuf, T* retbuf, T* combine_out,
                                     T* rnlp1, T* rnlp2, T* Rvec, T* out) {
      get_rnlp_device(p, K, npt, quad_x, quad_w, hgT2k, n, lx - 1, leftbuf, retbuf, combine_out);
      for (size_type i = thread_id(); i < 2 * K; i += block_size()) rnlp1[i] = retbuf[i];
      SYNCTHREADS();
      get_rnlp_device(p, K, npt, quad_x, quad_w, hgT2k, n, lx, leftbuf, retbuf, combine_out);
      for (size_type i = thread_id(); i < 2 * K; i += block_size()) rnlp2[i] = retbuf[i];
      SYNCTHREADS();

      T scale = exp2(T(-0.5) * T(n));
      for (size_type i = thread_id(); i < 2 * K; i += block_size()) {
        Rvec[i] = rnlp1[i] * scale;
        Rvec[2 * K + i] = rnlp2[i] * scale;
      }
      SYNCTHREADS();

      for (size_type idx = thread_id(); idx < K * K; idx += block_size()) {
        size_type qi = idx / K, qj = idx % K;
        T acc = T(0);
        for (size_type k = 0; k < 4 * K; ++k) acc += cten(qi, qj, k) * Rvec[k];
        out[idx] = acc;
      }
      SYNCTHREADS();
    }

    /**
     * Ported from mra::Convolution::make_nonstandard (misc/convolutiondata.h):
     * assembles the 2Kx2K child block from three rnlij matrices at the finer
     * level, applies the two-scale filter hgT (MADNESS's own
     * Convolution1D::hgT, 2K x 2K -- see conv_mad.h's extraction code) via
     * the same two-pass axis contraction mra::transform uses (verified
     * against mTxmq's contract, see this file's header comment), extracts S
     * as R's pre-transpose top-left KxK block, then transposes both R and S
     * (matching convolutiondata.h exactly). Writes R/S/norms directly into
     * item's destination views.
     *
     * Cooperative throughout: scalar/control-flow decisions (padding-slot,
     * unsupported-m, issmall checks) are redundantly identical on every
     * thread (cheap, and means no thread ever diverges from another at a
     * SYNCTHREADS()), while every matrix-valued step is a thread_id()-strided
     * loop over independent output elements writing into block-wide scratch
     * (`workspace`, sized by op1d_workspace_size(K) -- see
     * submit_generate_op1d_kernel), with a SYNCTHREADS() between any pair of
     * steps where one's output feeds the next's input. Every such step reads
     * a DIFFERENT buffer than it writes (never in-place), except the R/S
     * transpose, which is safe in place: each (i,j) with i<j is handled by
     * exactly one thread (the iteration skips i>=j), and that thread is the
     * only one that ever touches either (i,j) or (j,i). Norms reuse
     * mra::detail::normf(ptr, n) (mra/ops/functions.h) -- itself already a
     * cooperative, SYNCTHREADS-ed block reduction -- rather than hand-rolling
     * another one here.
     */
    template <typename T, concepts::TensorView<3> ViewC, concepts::TensorView<2> ViewHgT,
              concepts::TensorView<2> ViewHgT2k>
    DEVSCOPE void generate_op1d_one(const GenerateOp1DItem<T>& item, size_type K,
                                     const ViewC& cten,
                                     const ViewHgT& hgT,
                                     const ViewHgT2k& hgT2k,
                                     const T* quad_x, const T* quad_w, size_type npt,
                                     T* workspace) {
      const auto& p = item.params;
      auto R_dst = item.R_dst;
      auto S_dst = item.S_dst;
      auto norms_dst = item.norms_dst;

      // coeff==0 is the sentinel for a padding slot (i beyond a given count-index's
      // real separated-expansion rank, up to the batch-wide max rank -- see
      // conv_mad.h's work-item construction): a real Gaussian term never has an
      // exactly-zero coefficient (MADNESS's separated expansion simply wouldn't
      // include such a term), so this is unambiguous. m!=0 (derivative terms)
      // are not supported by this generator (see this file's header comment).
      // Both, like issmall(), just zero-fill -- matching make_op1d_shell's
      // existing host-side padding fill.
      if (p.coeff == T(0) || p.m != 0 || op1d_issmall(p.expnt, item.n, item.lx)) {
        if (p.coeff != T(0) && p.m != 0 && is_team_lead()) {
          THROWF("generate_op1d_one: derivative order m=%d is not supported by the device "
                 "generator (only plain m==0 Gaussian terms are)\n", p.m);
        }
        for (size_type idx = thread_id(); idx < 2 * K * 2 * K; idx += block_size())
          R_dst(idx / (2 * K), idx % (2 * K)) = T(0);
        for (size_type idx = thread_id(); idx < K * K; idx += block_size())
          S_dst(idx / K, idx % K) = T(0);
        if (is_team_lead()) {
          for (size_type f = 0; f < 5; ++f) norms_dst[f] = T(0);
        }
        SYNCTHREADS();
        return;
      }

      auto off = op1d_workspace_offsets(K);
      T* leftbuf = workspace + off.leftbuf;
      T* retbuf = workspace + off.retbuf;
      T* combine_out = workspace + off.combine_out;
      T* rnlp1 = workspace + off.rnlp1;
      T* rnlp2 = workspace + off.rnlp2;
      T* Rvec = workspace + off.Rvec;
      T* rm = workspace + off.rm;
      T* r0 = workspace + off.r0;
      T* rp = workspace + off.rp;
      T* tmp = workspace + off.tmp;
      T* t0 = workspace + off.t0;
      T* rmat = workspace + off.rmat;
      T* smat = workspace + off.smat;
      T* ns_scratch = workspace + off.ns_scratch;

      make_rnlij_device(p, K, npt, quad_x, quad_w, hgT2k, cten, item.n + 1, 2 * item.lx - 1,
                         leftbuf, retbuf, combine_out, rnlp1, rnlp2, Rvec, rm);
      make_rnlij_device(p, K, npt, quad_x, quad_w, hgT2k, cten, item.n + 1, 2 * item.lx,
                         leftbuf, retbuf, combine_out, rnlp1, rnlp2, Rvec, r0);
      make_rnlij_device(p, K, npt, quad_x, quad_w, hgT2k, cten, item.n + 1, 2 * item.lx + 1,
                         leftbuf, retbuf, combine_out, rnlp1, rnlp2, Rvec, rp);

      // Assemble the 2Kx2K child block from rm/r0/rp: read-only inputs, tmp
      // the sole (distinct) output -- no in-place-aliasing hazard.
      for (size_type idx = thread_id(); idx < K * K; idx += block_size()) {
        size_type i = idx / K, j = idx % K;
        tmp[i * (2 * K) + j] = r0[i * K + j];
        tmp[i * (2 * K) + K + j] = rm[i * K + j];
        tmp[(K + i) * (2 * K) + j] = rp[i * K + j];
        tmp[(K + i) * (2 * K) + K + j] = r0[i * K + j];
      }
      SYNCTHREADS();

      // R = hgT^T @ tmp @ hgT via two-pass axis contraction (see header
      // comment above get_rnlp_device for the mTxmq-derived verification of
      // this convention). Each pass reads one buffer and writes a different
      // one (tmp->t0, then t0->rmat).
      for (size_type idx = thread_id(); idx < 2 * K * 2 * K; idx += block_size()) {
        size_type i = idx / (2 * K), j = idx % (2 * K);
        T acc = T(0);
        for (size_type k = 0; k < 2 * K; ++k) acc += tmp[k * (2 * K) + i] * hgT(k, j);
        t0[idx] = acc;
      }
      SYNCTHREADS();
      for (size_type idx = thread_id(); idx < 2 * K * 2 * K; idx += block_size()) {
        size_type i = idx / (2 * K), j = idx % (2 * K);
        T acc = T(0);
        for (size_type k = 0; k < 2 * K; ++k) acc += t0[k * (2 * K) + i] * hgT(k, j);
        rmat[idx] = acc;
      }
      SYNCTHREADS();

      // S = R's pre-transpose top-left KxK block.
      for (size_type idx = thread_id(); idx < K * K; idx += block_size()) {
        size_type i = idx / K, j = idx % K;
        smat[idx] = rmat[i * (2 * K) + j];
      }
      SYNCTHREADS();

      // Transpose R (2Kx2K) and S (KxK) in place, matching convolutiondata.h
      // -- safe in place, see this function's header comment.
      for (size_type idx = thread_id(); idx < 2 * K * 2 * K; idx += block_size()) {
        size_type i = idx / (2 * K), j = idx % (2 * K);
        if (i < j) {
          T v = rmat[i * (2 * K) + j];
          rmat[i * (2 * K) + j] = rmat[j * (2 * K) + i];
          rmat[j * (2 * K) + i] = v;
        }
      }
      for (size_type idx = thread_id(); idx < K * K; idx += block_size()) {
        size_type i = idx / K, j = idx % K;
        if (i < j) {
          T v = smat[i * K + j];
          smat[i * K + j] = smat[j * K + i];
          smat[j * K + i] = v;
        }
      }
      SYNCTHREADS();

      // NSnormf needs R with its top-left KxK block zeroed; build that into
      // its own scratch region rather than mutating rmat (still needed below
      // for R_dst and Rnormf). Zeroing commutes with the transpose above
      // since that block maps to itself under it.
      for (size_type idx = thread_id(); idx < 2 * K * 2 * K; idx += block_size()) {
        size_type i = idx / (2 * K), j = idx % (2 * K);
        ns_scratch[idx] = (i < K && j < K) ? T(0) : rmat[idx];
      }
      SYNCTHREADS();

      T rnormf = normf(rmat, 2 * K * 2 * K);
      T snormf = normf(smat, K * K);
      T nsnormf = normf(ns_scratch, 2 * K * 2 * K);

      for (size_type idx = thread_id(); idx < 2 * K * 2 * K; idx += block_size())
        R_dst(idx / (2 * K), idx % (2 * K)) = rmat[idx];
      for (size_type idx = thread_id(); idx < K * K; idx += block_size())
        S_dst(idx / K, idx % K) = smat[idx];

      if (is_team_lead()) {
        // norms_dst order: Rnorm, Snorm, Rnormf, Snormf, NSnormf (see conv_mad.h's NormId).
        norms_dst[0] = sqrt(T(2 * K)) * rnormf; // Rnorm: conservative bound, not MADNESS's exact
        norms_dst[1] = sqrt(T(K)) * snormf;     // Snorm: SVD nuclear norm -- see header comment.
        norms_dst[2] = rnormf;
        norms_dst[3] = snormf;
        norms_dst[4] = nsnormf;
      }
      SYNCTHREADS();
    }

  } // namespace detail

  /// Total per-item scratch size (elements of T) that submit_generate_op1d_kernel
  /// expects via `workspace` -- see GaussianConvolutionOperator::submit_generation_kernel
  /// in conv_mad.h, which must allocate (and select()) workspace_size(K)*n_items.
  SCOPE size_type generate_op1d_workspace_size(size_type K) {
    return detail::op1d_workspace_offsets(K).total;
  }

  /**
   * One combined launch generating every item in `items` (device pointer,
   * size n_items) -- an arbitrary flattened worklist, so this single kernel
   * covers however many (term, dimension, level, translation) entries a
   * caller has collected, whether that's one task's own multiple missing
   * dimensions or (in a future iteration) many sibling tasks' missing
   * entries collected via a ttg::device::coop() rendezvous -- see
   * mra/misc/conv_mad.h. One block per item (grid-stride); within a block,
   * work is distributed cooperatively across all its threads -- see
   * generate_op1d_one's header comment. `workspace` must have room for
   * n_items * generate_op1d_workspace_size(K) elements; each grid-stride
   * iteration uses its own disjoint per-item slice, so (unlike a scheme that
   * reused one region per block across iterations) no synchronization is
   * needed between items, only within a single item's own generate_op1d_one
   * call.
   */
  template <typename T, concepts::TensorView<3> ViewC, concepts::TensorView<2> ViewHgT,
            concepts::TensorView<2> ViewHgT2k>
  LAUNCH_BOUNDS(MAX_THREADS_PER_BLOCK)
  GLOBALSCOPE void generate_op1d_kernel(
      const GenerateOp1DItem<T>* items, size_type n_items, size_type K,
      ViewC c, ViewHgT hgT,
      ViewHgT2k hgT2k, const T* quad_x, const T* quad_w, size_type npt,
      T* workspace) {
    const size_type ws_size = generate_op1d_workspace_size(K);
    for (size_type idx = blockIdx.x; idx < n_items; idx += gridDim.x) {
      detail::generate_op1d_one<T>(items[idx], K, c, hgT, hgT2k, quad_x, quad_w, npt,
                                    workspace + idx * ws_size);
    }
  }

  /**
   * Host-side launcher. `items` must already be resident on the current
   * device (n_items entries); `c`/`hgT`/`hgT2k`/`quad_x`/`quad_w` are the
   * shared (not per-item) tensors extracted once at operator construction
   * (see conv_mad.h). `workspace` must be a device pointer with room for
   * n_items * generate_op1d_workspace_size(K) elements (see
   * GaussianConvolutionOperator::submit_generation_kernel in conv_mad.h,
   * which allocates and select()s it). Thread block sized by K via the same
   * max_thread_dims() helper submit_convolution_kernel uses, since the
   * per-item work is now genuinely distributed across the block -- see
   * generate_op1d_one's header comment.
   */
  template <typename T, concepts::TensorView<3> ViewC, concepts::TensorView<2> ViewHgT,
            concepts::TensorView<2> ViewHgT2k>
  void submit_generate_op1d_kernel(
      const GenerateOp1DItem<T>* items, size_type n_items, size_type K,
      const ViewC& c, const ViewHgT& hgT,
      const ViewHgT2k& hgT2k, const T* quad_x, const T* quad_w, size_type npt,
      T* workspace,
      ttg::device::Stream stream) {
    if (n_items == 0) return;
    Dim3 thread_dims = max_thread_dims(2 * K);
    CALL_KERNEL((generate_op1d_kernel<T, ViewC, ViewHgT, ViewHgT2k>), n_items, thread_dims, 0, stream,
                (items, n_items, K, c, hgT, hgT2k, quad_x, quad_w, npt, workspace));
    checkSubmit();
  }

  /**
   * Packs a host-side list of work items into a fresh ttg::Buffer, ready to
   * be select()-ed and passed to submit_generate_op1d_kernel. Kept as a free
   * function (not a coroutine) since only the caller's own device-task body
   * can co_await -- see conv_mad.h's GaussianConvolutionOperator header
   * comment.
   */
  template <typename T>
  ttg::Buffer<GenerateOp1DItem<T>> make_generate_op1d_items_buffer(
      const std::vector<GenerateOp1DItem<T>>& items) {
    auto ptr = std::shared_ptr<GenerateOp1DItem<T>[]>(new GenerateOp1DItem<T>[items.size()]);
    std::copy(items.begin(), items.end(), ptr.get());
    return ttg::Buffer<GenerateOp1DItem<T>>(std::move(ptr), items.size());
  }

} // namespace mra

#endif // MRA_KERNELS_GENERATE_OP1D_H
