#ifndef MRA_KERNELS_GENERATE_OP1D_H
#define MRA_KERNELS_GENERATE_OP1D_H

/**
 * On-device generation of the per-(level, dimension, translation) 1D
 * transition-matrix tensors (R, S, and their norms) used by the convolution
 * operator (see mra/misc/conv_mad.h). This replaces calling into MADNESS's
 * Convolution1D::nonstandard() on the CPU -- the actual bottleneck that
 * motivated this file: that CPU work sat on the critical path of a device
 * task and could not keep the GPU busy.
 *
 * The math is ported from mra::Convolution in mra/misc/convolutiondata.h
 * (a from-scratch, MADNESS-free CPU reference implementing the same
 * quadrature-projection / autocorrelation / two-scale-filter algorithm),
 * generalized to take the per-term Gaussian parameters (coeff, expnt,
 * natlev) and the shared autocorrelation/two-scale-filter tensors as
 * arguments instead of owning them, so the *many* separated-expansion terms
 * of a real operator (extracted once, on the host, from MADNESS's
 * GaussianConvolution1D -- see conv_mad.h) can all be generated by one
 * kernel launch.
 *
 * Known limitations of this first pass (see mra/misc/conv_mad.h for the
 * fuller rationale):
 *  - Only plain (m==0) Gaussian terms are supported; derivative operators
 *    (m==1,2) are not generated here.
 *  - Rnorm/Snorm are NOT MADNESS's exact SVD-based nuclear norm (that would
 *    require an on-device SVD). Instead we use the standard bound
 *    ||A||_nuclear <= sqrt(n) * ||A||_F, i.e. Rnorm_approx = sqrt(2K)*Rnormf,
 *    Snorm_approx = sqrt(K)*Snormf. This can only make the application
 *    kernel's screening MORE conservative than MADNESS's tighter bound
 *    (never wrongly skips a term that should contribute) -- a performance
 *    cost, not a correctness one.
 */

#include "mra/misc/platform.h"
#include "mra/misc/types.h"
#include "mra/misc/maxk.h"
#include "mra/tensor/tensorview.h"
#include "mra/ops/functions.h" // for mra::detail::normf -- cooperative block-wide reduction, reused below

/**
 * Upper bound on get_rnlp_device's tree depth (natlev - n). MADNESS itself
 * never uses tree levels beyond MAX_LEVEL == 31 (see the KeyPair::hash()
 * comment in mra/tasks/convolution.h), so no legitimate (n, natlev) pair can
 * need to descend further than that -- this is a real, meaningful bound, not
 * an arbitrary guess. Overridable like MRA_MAX_K for the same reason.
 */
#ifndef MRA_OP1D_MAX_RECURSION_DEPTH
#define MRA_OP1D_MAX_RECURSION_DEPTH 64
#endif // MRA_OP1D_MAX_RECURSION_DEPTH

namespace mra {

  /**
   * Per-term Gaussian parameters, extracted ONCE (at GaussianConvolutionOperator
   * construction, on the host) from MADNESS's GaussianConvolution1D -- see
   * conv_mad.h's extraction code. Tiny POD, travels by value per work item
   * (the same way tol/at already travel per-member in ConvolutionBatchArg,
   * see mra/kernels/convolution.h) rather than through a Tensor/Buffer.
   */
  template <typename T>
  struct GaussianTermParams {
    T coeff = T(0);
    T fac = T(0);
    T expnt = T(0);
    Level natlev = 0;
    int m = 0; // derivative order; only m==0 is generated on device (see above)
  };

  /**
   * A frame in the recursive call stack. We cannot rely on recursive calls in the kernel
   * so we use a manual stack approach instead. The stack is located in shared memory.
   */
  enum FrameState : unsigned char { ENTER, WAIT_LEFT, WAIT_RIGHT };
  struct Frame {
    Level n;
    Translation lx;
    FrameState state;
  };


  /**
   * One (term, dimension, count-index) unit of work: generate R/S and their
   * norms for EVERY translation lx in [lmin, lmax] at level n, writing into
   * this item's own (d, *, c, i) slice of the shared, level-wide R/S/norms1d
   * views (see detail::LevelOp1DTable in conv_mad.h) -- the kernel receives
   * those full views directly (see generate_op1d_kernel/submit_generate_op1d_kernel)
   * rather than each item carrying its own already-sliced destination view,
   * so there's one buffer per field to select() regardless of how many
   * items or translations a launch covers. Trivially copyable (plain
   * scalars only), so a std::vector of these can be uploaded with one H2D
   * copy, same as any other batch-arg struct in this codebase.
   */
  template <typename T>
  struct GenerateOp1DItem {
    GaussianTermParams<T> params;
    Level n = 0;
    Translation lmin = 0;
    Translation lmax = 0;
    Dimension d = 0;
    size_type c = 0;
    size_type i = 0;
  };

  namespace detail {

    /// Ported from mra::Convolution::issmall (misc/convolutiondata.h).
    template <typename T>
    DEVSCOPE bool op1d_issmall(T expnt, Level n, Translation lx) {
      T beta = expnt * exp2(T(-2) * T(n));
      Translation l;
      if (lx > 0) l = lx - 1;
      else if (lx < 0) l = -lx - 1;
      else l = 0;
      return beta * T(l) * T(l) > T(49.0);
    }

    /// Ported from legendre_scaling_functions (src/gl.cc), which is host-only
    /// (backed by a host-resident normalization table) -- this is the
    /// device-portable equivalent, computed directly instead of from a table
    /// since the recurrence coefficients (n/(n+1), sqrt(2n+1)) are cheap to
    /// evaluate inline. p must have room for k elements.
    ///
    /// Sequential and thread-private: the three-term recurrence makes p[n+1]
    /// depend on p[n] and p[n-1], so it cannot be split across threads, and k
    /// (at most 2*MRA_MAX_K) is small enough for every thread to evaluate it
    /// redundantly into its own `p`.
    template <typename T>
    DEVSCOPE void legendre_scaling_device(T x, size_type k, T* p) {
      T z = T(2) * x - T(1);
      p[0] = T(1);
      if (k > 1) p[1] = z;
      for (size_type n = 1; n + 1 < k; ++n) {
        T nn1 = T(n) / T(n + 1);
        p[n + 1] = (z * p[n] - p[n - 1]) * nn1 + z * p[n];
      }
      for (size_type n = 0; n < k; ++n) {
        p[n] *= sqrt(T(2) * T(n) + T(1));
      }
    }

    /**
     * Per-item scratch layout for the cooperative generator below. Every
     * region is block-wide -- written and read by every thread in the
     * block, via caller-allocated GLOBAL memory (one region per work item,
     * sized by op1d_workspace_size(K) and indexed by the item's position in
     * the batch -- see submit_generate_op1d_kernel). Deliberately not CUDA
     * __shared__ memory: that would need either compile-time sizing (K is a
     * runtime value here) or an extern-shared/pointer-carving scheme, plus
     * it runs into the team-lead-only-SHARED-rebind-before-SYNCTHREADS nvcc
     * miscompile pitfall already flagged elsewhere in this codebase (see
     * e.g. compress_process_one_leader's comment in kernels/compress.h).
     * Plain per-item global memory sidesteps both at a modest bandwidth
     * cost -- acceptable here since generation is not the hot loop this
     * whole effort is trying to keep off (that's MADNESS's CPU-side
     * nonstandard() call; see this file's header comment).
     */
    struct Op1DWorkspaceOffsets {
      size_type leftbuf;     // [MRA_OP1D_MAX_RECURSION_DEPTH][2K]
      size_type retbuf;      // [2K]
      size_type combine_out; // [2K] -- see get_rnlp_device's WAIT_RIGHT comment for why this must
                              // be distinct from retbuf/leftbuf, not an in-place combine target
      size_type rnlp1;       // [2K]
      size_type rnlp2;       // [2K]
      size_type Rvec;        // [4K]
      size_type rm;          // [K*K]
      size_type r0;          // [K*K]
      size_type rp;          // [K*K]
      size_type tmp;         // [2K*2K]
      size_type t0;          // [2K*2K]
      size_type rmat;        // [2K*2K]
      size_type smat;        // [K*K]
      size_type ns_scratch;  // [2K*2K]
      size_type total;

      SCOPE Op1DWorkspaceOffsets(auto K)
      {
        size_type p = 0;
        leftbuf = p; p += MRA_OP1D_MAX_RECURSION_DEPTH * 2 * K;
        retbuf = p; p += 2 * K;
        combine_out = p; p += 2 * K;
        rnlp1 = p; p += 2 * K;
        rnlp2 = p; p += 2 * K;
        Rvec = p; p += 4 * K;
        rm = p; p += K * K;
        r0 = p; p += K * K;
        rp = p; p += K * K;
        tmp = p; p += 2 * K * 2 * K;
        t0 = p; p += 2 * K * 2 * K;
        rmat = p; p += 2 * K * 2 * K;
        smat = p; p += K * K;
        ns_scratch = p; p += 2 * K * 2 * K;
        total = p;
      }
    };

    SCOPE Op1DWorkspaceOffsets op1d_workspace_offsets(size_type K) {
      Op1DWorkspaceOffsets o{K};
      return o;
    }

    /// Ported from mra::Convolution::make_rnlp (misc/convolutiondata.h): the
    /// leaf (base-case) quadrature projection of the Gaussian onto
    /// double-order polynomials. `out` is block-wide (shared) scratch with
    /// room for 2*K elements.
    ///
    /// Cooperative along two axes: threadIdx.x owns an output coefficient p
    /// (blockDim.x == 2*K exactly, see max_thread_dims(2*K) in
    /// submit_generate_op1d_kernel, so this needs no stride on device -- the
    /// stride is still there for the host build, where blockDim.x == 1 and
    /// one "thread" must walk all 2*K of them), while threadIdx.y owns a
    /// strided slice of the (box, quadrature-point) work -- previously that
    /// whole double loop was walked redundantly by every one of the up to
    /// 2*K*2*K threads in the block, yet only the 2*K threads with
    /// threadIdx.y == 0 ever contributed (the rest fell outside `out`'s
    /// thread_id()-strided publication range and did nothing useful).
    /// Flattening (box, i) into one index lets every row stride over it
    /// independently; box is non-decreasing in that flattened index, so a
    /// row's own early-exit once beta*xlo*xlo crosses argmax is still exact,
    /// just evaluated per row instead of once globally. Each (p, row) thread
    /// accumulates its own private partial sum (still redundantly computing
    /// the full `phix` vector per point, same as before, to avoid a
    /// reduction/atomics over that intermediate); rows are then reduced into
    /// `out[p]` after a sync, via the per-row partial sums held in `acc`.
    template <typename T>
    DEVSCOPE void make_rnlp_leaf(T coeff, T expnt, size_type K, size_type npt,
                                  const T* quad_x, const T* quad_w,
                                  Level n, Translation lx, T* tmp, T* out) {
      Translation lkeep = lx;
      Translation lxx = (lx < 0) ? (-lx - 1) : lx;
      T scaledcoeff = coeff * exp2(T(-0.5) * T(n));
      T beta = expnt * exp2(T(-2) * T(n));
      T h = T(1) / sqrt(beta);
      size_type nbox = std::max(size_type(1), size_type(T(1) / h));
      h = T(1) / T(nbox);
      T sch = fabs(scaledcoeff * h);
      T argmax = fabs(log(T(1e-22) / sch));

      // acc[row][p]: one partial sum per (row, output coefficient), reduced
      // across rows below. Bounded by 2*MRA_MAX_K in both dimensions, same
      // as the 2K x 2K scratch (tmp/t0/rmat/ns_scratch) used elsewhere in
      // this file -- blockDim.y <= 2*K <= 2*MRA_MAX_K always.
      //SHARED T acc[2 * MRA_MAX_K_SIZET][2 * MRA_MAX_K_SIZET];
      T (*acc)[2 * MRA_MAX_K_SIZET] = (T (*)[2 * MRA_MAX_K_SIZET])tmp;
      T phix[2 * MRA_MAX_K_SIZET]; // thread-private, see legendre_scaling_device

      const size_type row = (size_type)threadIdx.y;
      const size_type nrows = (size_type)blockDim.y;
      const size_type total_work = nbox * npt;

      for (size_type p = threadIdx.x; p < 2 * K; p += blockDim.x) {
        T a = T(0);
        for (size_type w = row; w < total_work; w += nrows) {
          size_type box = w / npt, i = w % npt;
          T xlo = T(box) * h + T(lxx);
          if (beta * xlo * xlo > argmax) break; // box is non-decreasing in w -- safe early exit for this row
          T xx = xlo + h * quad_x[i];
          T ee = scaledcoeff * exp(-beta * xx * xx) * quad_w[i] * h;
          legendre_scaling_device(xx - T(lxx), 2 * K, phix);
          a += ee * phix[p];
        }
        acc[row][p] = a;
      }
      SYNCTHREADS();

      if (row == 0) {
        for (size_type p = threadIdx.x; p < 2 * K; p += blockDim.x) {
          T s = T(0);
          for (size_type r = 0; r < nrows; ++r) s += acc[r][p];
          if (lkeep < 0 && (p & 1)) s = -s; // odd coefficients flip sign for negative translations
          out[p] = s;
        }
      }
      SYNCTHREADS();
    }

    /**
     * Ported from mra::Convolution::get_rnlp (misc/convolutiondata.h):
     * projects onto a finer level (via the order-2K two-scale filter hgT2k,
     * exactly MADNESS's own Convolution1D::hgT2k -- see conv_mad.h's
     * extraction code) until issmall() cuts it off or the Gaussian's natural
     * level is reached, then falls back to the leaf quadrature sum. On
     * return, `retbuf` (block-wide scratch, 2*K elements) holds the answer.
     *
     * The combine step's contraction (out[j] = sum_k tmp[k]*hgT2k(k,j)) is
     * mra::transform's convention for a 1D input, verified directly against
     * mTxmq's documented contract (mra/ops/mxm.h: c(i,j)=sum_k a(k,i)*b(k,j),
     * here dimi==1) rather than re-derived from the generic (NDIM-tensor)
     * mra::transform helper -- see this file's header comment.
     *
     * Implemented as an explicit-stack post-order traversal rather than true
     * recursion (the conceptual algorithm is still exactly the recursive one
     * -- two child calls at (n+1, 2*lx) / (n+1, 2*lx+1), combined via
     * hgT2k). A real recursive __device__ function makes per-thread local-
     * memory/stack sizing unpredictable for the compiler (and risks a
     * runtime stack overflow across many concurrent threads if actual depth
     * exceeds whatever nvcc assumed); this version's control-flow state is a
     * fixed, statically-sized, per-thread-PRIVATE array instead --
     * MRA_OP1D_MAX_RECURSION_DEPTH frames, each just a small (n, lx, state)
     * triple. Kept private (redundantly identical on every thread, since it
     * depends only on scalar inputs shared by the whole block) rather than
     * promoted to the block-wide `leftbuf`/`retbuf`/`combine_out` scratch,
     * which hold the actual numerical results and are the only things that
     * need synchronization.
     *
     * Each frame starts ENTER (not yet processed): issmall() prunes it to a
     * zero leaf immediately; n>=natlev makes it a quadrature leaf; otherwise
     * it's an internal node -- push the left child (frame state becomes
     * WAIT_LEFT) and let the loop resolve it (however deep that takes,
     * within the same fixed stack). When a WAIT_LEFT frame is revisited (only
     * possible immediately after its child popped, so retbuf reliably holds
     * that child's result, synchronized), stash it into leftbuf[top] and
     * push the right child (state becomes WAIT_RIGHT). When a WAIT_RIGHT
     * frame is revisited, retbuf holds the right child's result; combine it
     * with leftbuf[top] via hgT2k into combine_out (a buffer distinct from
     * both inputs -- every thread's output index reads the FULL 4K
     * concatenated vector, so overwriting either input in place while other
     * threads may still be reading it would race), then copy combine_out
     * back into retbuf for the parent to consume. When the stack empties,
     * retbuf holds the original (n0, lx0) query's answer.
     */
    template <typename T, concepts::TensorView<2> ViewHgT2k>
    DEVSCOPE void get_rnlp_device(const GaussianTermParams<T>& p, size_type K, size_type npt,
                                   const T* quad_x, const T* quad_w,
                                   const ViewHgT2k& hgT2k,
                                   Level n0, Translation lx0,
                                   T* leftbuf, T* retbuf, T* combine_out,
                                   T* tmp, Frame* stack) {
      size_type sp = 0;
      if (is_team_lead()) {
        stack[sp].n = n0;
        stack[sp].lx = lx0;
        stack[sp].state = ENTER;
      }
      SYNCTHREADS();
      ++sp;

      while (sp > 0) {
        const size_type top = sp - 1;
        // Snapshot the frame, then synchronize: the team lead updates
        // stack[top].state below, and a thread that had not read it yet would
        // otherwise see the new state and take a different branch (and a
        // different SYNCTHREADS()) than the rest of the block.
        const Frame f = stack[top];
        SYNCTHREADS();

        if (f.state == ENTER) {
          if (op1d_issmall(p.expnt, f.n, f.lx)) {
            for (size_type i = thread_id(); i < 2 * K; i += block_size()) retbuf[i] = T(0);
            SYNCTHREADS();
            --sp;
            continue;
          }
          if (f.n < p.natlev) {
            if (is_team_lead()) {
              stack[top].state = WAIT_LEFT;
            }
            SYNCTHREADS();
            if (sp >= MRA_OP1D_MAX_RECURSION_DEPTH) {
              if (is_team_lead()) {
                THROWF("get_rnlp_device: recursion depth exceeded MRA_OP1D_MAX_RECURSION_DEPTH (%d)\n",
                       MRA_OP1D_MAX_RECURSION_DEPTH);
              }
              return;
            }
            if (is_team_lead()) {
              stack[sp].n = f.n + 1;
              stack[sp].lx = 2 * f.lx;
              stack[sp].state = ENTER;
            }
            SYNCTHREADS();
            ++sp;
            continue;
          }
          make_rnlp_leaf(p.coeff, p.expnt, K, npt, quad_x, quad_w, f.n, f.lx, tmp, retbuf); // already synced internally
          --sp;
          continue;
        }

        if (f.state == WAIT_LEFT) {
          for (size_type i = thread_id(); i < 2 * K; i += block_size())
            leftbuf[top * 2 * K + i] = retbuf[i];
          if (is_team_lead()) {
            stack[top].state = WAIT_RIGHT;
          }
          SYNCTHREADS();
          if (sp >= MRA_OP1D_MAX_RECURSION_DEPTH) {
            if (is_team_lead()) {
              THROWF("get_rnlp_device: recursion depth exceeded MRA_OP1D_MAX_RECURSION_DEPTH (%d)\n",
                     MRA_OP1D_MAX_RECURSION_DEPTH);
            }
            return;
          }
          if (is_team_lead()) {
            stack[sp].n = f.n + 1;
            stack[sp].lx = 2 * f.lx + 1;
            stack[sp].state = ENTER;
          }
          SYNCTHREADS();
          ++sp;
          continue;
        }

        // f.state == WAIT_RIGHT: retbuf holds the right child's result,
        // leftbuf[top] the (already-computed) left child's. Parallelized the
        // same way as make_rnlp_leaf: threadIdx.x owns an output index j
        // (blockDim.x == 2*K exactly, so this needs no stride on device --
        // see make_rnlp_leaf's comment), while threadIdx.y splits the 4*K-
        // term contraction (leftbuf/retbuf concatenated against hgT2k's
        // matching 4*K rows) across rows, each row's partial sum landing in
        // tmp (reinterpreted as [row][j] scratch -- safe to reuse: tmp is
        // otherwise untouched for the whole make_rnlij_device/
        // get_rnlp_device call chain, see make_rnlp_leaf's own comment),
        // reduced into combine_out afterward. Safe to sync right after the
        // j-loop (no per-iteration barrier needed) because j's loop always
        // takes exactly one trip per thread on device -- its range (2*K)
        // equals blockDim.x exactly, unlike make_rnlij_device's K*K-sized
        // contraction below, which needs a wave loop instead.
        {
          const size_type row = (size_type)threadIdx.y;
          const size_type nrows = (size_type)blockDim.y;
          T (*acc)[2 * MRA_MAX_K_SIZET] = (T (*)[2 * MRA_MAX_K_SIZET])tmp;

          for (size_type j = threadIdx.x; j < 2 * K; j += blockDim.x) {
            T a = T(0);
            for (size_type k = row; k < 4 * K; k += nrows) {
              T src = (k < 2 * K) ? leftbuf[top * 2 * K + k] : retbuf[k - 2 * K];
              a += src * hgT2k(k, j);
            }
            acc[row][j] = a;
          }
          SYNCTHREADS();
          if (row == 0) {
            for (size_type j = threadIdx.x; j < 2 * K; j += blockDim.x) {
              T s = T(0);
              for (size_type r = 0; r < nrows; ++r) s += acc[r][j];
              combine_out[j] = s;
            }
          }
          SYNCTHREADS();
          for (size_type j = thread_id(); j < 2 * K; j += block_size()) retbuf[j] = combine_out[j];
          SYNCTHREADS();
          --sp;
        }
      }
      // retbuf now holds the (n0, lx0) query's answer -- caller reads it directly.
    }

    /**
     * Ported from mra::Convolution::make_rnlij (misc/convolutiondata.h):
     * projects the Gaussian onto the KxK "rnlij" block via an inner product
     * against the autocorrelation tensor c (4K x K x K here -- MADNESS's own
     * Convolution1D::c is K x K x 4K; conv_mad.h's extraction transposes it
     * once, on the host, so the contraction axis k is OUTERMOST and (qi,qj)
     * are contiguous -- see extract_gaussian_terms_for_device()'s comment --
     * so that consecutive threads working on consecutive (qi,qj) for the
     * same k below hit consecutive addresses instead of ones 4K apart).
     * `out` (block-wide scratch, K*K elements, row-major out[qi*K+qj]) holds
     * the result on return.
     *
     * The contraction is out(qi,qj) = sum_k c(k,qi,qj)*Rvec[k] -- the same
     * math as MADNESS's c(qi,qj,k)*Rvec[k], just reading the transposed
     * layout above.
     *
     * leftbuf/retbuf/combine_out are get_rnlp_device's own scratch (passed
     * through); rnlp1/rnlp2/Rvec are this function's own block-wide scratch.
     */
    template <typename T, concepts::TensorView<2> ViewHgT2k, concepts::TensorView<3> ViewC>
    DEVSCOPE void make_rnlij_device(const GaussianTermParams<T>& p, size_type K, size_type npt,
                                     const T* quad_x, const T* quad_w,
                                     const ViewHgT2k& hgT2k,
                                     const ViewC& cten,
                                     Level n, Translation lx,
                                     T* leftbuf, T* retbuf, T* combine_out,
                                     T* rnlp1, T* rnlp2, T* Rvec, T* out, T* tmp, Frame* stack) {
      get_rnlp_device(p, K, npt, quad_x, quad_w, hgT2k, n, lx - 1, leftbuf, retbuf, combine_out, tmp, stack);
      for (size_type i = thread_id(); i < 2 * K; i += block_size()) rnlp1[i] = retbuf[i];
      SYNCTHREADS();
      get_rnlp_device(p, K, npt, quad_x, quad_w, hgT2k, n, lx, leftbuf, retbuf, combine_out, tmp, stack);
      for (size_type i = thread_id(); i < 2 * K; i += block_size()) rnlp2[i] = retbuf[i];
      SYNCTHREADS();

      T scale = exp2(T(-0.5) * T(n));
      for (size_type i = thread_id(); i < 2 * K; i += block_size()) {
        Rvec[i] = rnlp1[i] * scale;
        Rvec[2 * K + i] = rnlp2[i] * scale;
      }
      SYNCTHREADS();

      // Parallelize the 4*K-term reduction too, same idea as get_rnlp_device's
      // combine step above: threadIdx.x owns an output index, threadIdx.y
      // splits the reduction over k across rows into tmp-backed scratch
      // (safe to reuse -- the earlier get_rnlp_device calls that also use
      // tmp have already returned and been fully synced by this point),
      // reduced after a sync. Unlike that combine step, K*K generally isn't
      // a multiple of blockDim.x (==2*K), so threadIdx.x-striding this with
      // a single SYNCTHREADS() after the loop would give lanes an UNEVEN
      // number of loop trips -- and a SYNCTHREADS() reached a different
      // number of times by different threads is a hang, not a wrong answer.
      // Instead every thread runs exactly nwaves iterations (nwaves depends
      // only on K and blockDim.x, both uniform across the block), masking
      // the tail wave's out-of-range lanes with `idx < K*K` around the work
      // only, never around the syncs.
      {
        const size_type row = (size_type)threadIdx.y;
        const size_type nrows = (size_type)blockDim.y;
        const size_type ncols = (size_type)blockDim.x; // == 2*K
        const size_type nwaves = (K * K + ncols - 1) / ncols;
        T (*acc)[2 * MRA_MAX_K_SIZET] = (T (*)[2 * MRA_MAX_K_SIZET])tmp;

        for (size_type wave = 0; wave < nwaves; ++wave) {
          const size_type idx = wave * ncols + threadIdx.x;
          T a = T(0);
          if (idx < K * K) {
            size_type qi = idx / K, qj = idx % K;
            for (size_type k = row; k < 4 * K; k += nrows) a += cten(k, qi, qj) * Rvec[k];
          }
          acc[row][threadIdx.x] = a;
          SYNCTHREADS();
          if (row == 0 && idx < K * K) {
            T s = T(0);
            for (size_type r = 0; r < nrows; ++r) s += acc[r][threadIdx.x];
            out[idx] = s;
          }
          SYNCTHREADS();
        }
      }
    }

    /**
     * Ported from mra::Convolution::make_nonstandard (misc/convolutiondata.h):
     * assembles the 2Kx2K child block from three rnlij matrices at the finer
     * level, applies the two-scale filter hgT (MADNESS's own
     * Convolution1D::hgT, 2K x 2K -- see conv_mad.h's extraction code) via
     * the same two-pass axis contraction mra::transform uses (verified
     * against mTxmq's contract, see this file's header comment), extracts S
     * as R's pre-transpose top-left KxK block, then transposes both R and S
     * (matching convolutiondata.h exactly). Writes R/S/norms directly into
     * item's destination views.
     *
     * Cooperative throughout: scalar/control-flow decisions (padding-slot,
     * unsupported-m, issmall checks) are redundantly identical on every
     * thread (cheap, and means no thread ever diverges from another at a
     * SYNCTHREADS()), while every matrix-valued step is a thread_id()-strided
     * loop over independent output elements writing into block-wide scratch
     * (`workspace`, sized by op1d_workspace_size(K) -- see
     * submit_generate_op1d_kernel), with a SYNCTHREADS() between any pair of
     * steps where one's output feeds the next's input. Every such step reads
     * a DIFFERENT buffer than it writes (never in-place), except the R/S
     * transpose, which is safe in place: each (i,j) with i<j is handled by
     * exactly one thread (the iteration skips i>=j), and that thread is the
     * only one that ever touches either (i,j) or (j,i). Norms reuse
     * mra::detail::normf(ptr, n) (mra/ops/functions.h) -- itself already a
     * cooperative, SYNCTHREADS-ed block reduction -- rather than hand-rolling
     * another one here.
     */
    template <typename T, concepts::TensorView<3> ViewC, concepts::TensorView<2> ViewHgT,
              concepts::TensorView<2> ViewHgT2k, concepts::TensorView<6> ViewR, concepts::TensorView<6> ViewS,
              concepts::TensorView<5> ViewNorms>
    DEVSCOPE void generate_op1d_one(const GenerateOp1DItem<T>& item, Translation lx, size_type K,
                                     const ViewC& cten,
                                     const ViewHgT& hgT,
                                     const ViewHgT2k& hgT2k,
                                     const T* quad_x, const T* quad_w, size_type npt,
                                     T* workspace, Translation l_offset,
                                     ViewR& R, ViewS& S, ViewNorms& norms) {
      const auto& p = item.params;
      const size_type l_idx = (size_type)(lx + l_offset);
      auto R_dst = R(item.d, l_idx, item.c, item.i);
      auto S_dst = S(item.d, l_idx, item.c, item.i);
      auto norms_dst = norms(item.d, l_idx, item.c, item.i);

      // coeff==0 is the sentinel for a padding slot (i beyond a given count-index's
      // real separated-expansion rank, up to the batch-wide max rank -- see
      // conv_mad.h's work-item construction): a real Gaussian term never has an
      // exactly-zero coefficient (MADNESS's separated expansion simply wouldn't
      // include such a term), so this is unambiguous. m!=0 (derivative terms)
      // are not supported by this generator (see this file's header comment).
      if (p.coeff == T(0) || p.m != 0) {
        if (p.coeff != T(0) && p.m != 0 && is_team_lead()) {
          THROWF("generate_op1d_one: derivative order m=%d is not supported by the device "
                 "generator (only plain m==0 Gaussian terms are)\n", p.m);
        }
        for (size_type idx = thread_id(); idx < 2 * K * 2 * K; idx += block_size())
          R_dst(idx / (2 * K), idx % (2 * K)) = T(0);
        for (size_type idx = thread_id(); idx < K * K; idx += block_size())
          S_dst(idx / K, idx % K) = T(0);
        if (is_team_lead()) {
          for (size_type f = 0; f < 5; ++f) norms_dst[f] = T(0);
        }
        SYNCTHREADS();
        return;
      }

      auto off = op1d_workspace_offsets(K);
      //T* leftbuf = workspace + off.leftbuf;
      //T* retbuf = workspace + off.retbuf;
      //T* combine_out = workspace + off.combine_out;
      //T* rnlp1 = workspace + off.rnlp1;
      //T* rnlp2 = workspace + off.rnlp2;
      //T* Rvec = workspace + off.Rvec;
      //T* rm = workspace + off.rm;
      //T* r0 = workspace + off.r0;
      //T* rp = workspace + off.rp;
      //T* tmp = workspace + off.tmp;
      //T* t0 = workspace + off.t0;
      //T* rmat = workspace + off.rmat;
      //T* smat = workspace + off.smat;
      //T* ns_scratch = workspace + off.ns_scratch;

      // shared memory for the operation
      SHARED T leftbuf[MRA_OP1D_MAX_RECURSION_DEPTH * 2 * MRA_MAX_K];     // [MRA_OP1D_MAX_RECURSION_DEPTH][2K]
      SHARED T retbuf[2 * MRA_MAX_K];      // [2K]
      SHARED T combine_out[2 * MRA_MAX_K]; // [2K] -- see get_rnlp_device's WAIT_RIGHT comment for why this must be distinct from retbuf/leftbuf, not an in-place combine target
      SHARED T rnlp1[2 * MRA_MAX_K];       // [2K]
      SHARED T rnlp2[2 * MRA_MAX_K];       // [2K]
      SHARED T Rvec[4 * MRA_MAX_K];        // [4K]
      SHARED T rm[MRA_MAX_K * MRA_MAX_K];          // [K*K]
      SHARED T r0[MRA_MAX_K * MRA_MAX_K];          // [K*K]
      SHARED T rp[MRA_MAX_K * MRA_MAX_K];          // [K*K]

      /**
       * Temporary storage for intermediate results. Is used both for the accumulation buffer
       * in make_rnlp_leaf and below to assemble the 2k x 2k child blocks.
       */
      SHARED T tmp[2 * MRA_MAX_K * 2 * MRA_MAX_K]; // [2K x 2K]
      SHARED T t0[2 * MRA_MAX_K * 2 * MRA_MAX_K];  // [2K x 2K]
      // we can reuse tmp as rmat
      T* rmat = tmp; // [2K x 2K]
      SHARED T smat[MRA_MAX_K * MRA_MAX_K];        // [K x K]
      // we can reuse t0 as ns_scratch
      T* ns_scratch = t0; // [2K x 2K]

      if (op1d_issmall(p.expnt, item.n, lx)) {
        for (size_type idx = thread_id(); idx < 2 * K * 2 * K; idx += block_size())
          R_dst(idx / (2 * K), idx % (2 * K)) = T(0);
        for (size_type idx = thread_id(); idx < K * K; idx += block_size())
          S_dst(idx / K, idx % K) = T(0);
        if (is_team_lead()) {
          for (size_type f = 0; f < 5; ++f) norms_dst[f] = T(0);
        }
        SYNCTHREADS();
        return;
      }

      SHARED Frame stack[MRA_OP1D_MAX_RECURSION_DEPTH]; // per-thread private; see header comment

      make_rnlij_device(p, K, npt, quad_x, quad_w, hgT2k, cten, item.n + 1, 2 * lx - 1,
                         leftbuf, retbuf, combine_out, rnlp1, rnlp2, Rvec, rm, tmp, stack);
      make_rnlij_device(p, K, npt, quad_x, quad_w, hgT2k, cten, item.n + 1, 2 * lx,
                         leftbuf, retbuf, combine_out, rnlp1, rnlp2, Rvec, r0, tmp, stack);
      make_rnlij_device(p, K, npt, quad_x, quad_w, hgT2k, cten, item.n + 1, 2 * lx + 1,
                         leftbuf, retbuf, combine_out, rnlp1, rnlp2, Rvec, rp, tmp, stack);

      // Assemble the 2Kx2K child block from rm/r0/rp: read-only inputs, tmp
      // the sole (distinct) output -- no in-place-aliasing hazard.
      for (size_type idx = thread_id(); idx < K * K; idx += block_size()) {
        size_type qi = idx / K, qj = idx % K;
        tmp[qi * (2 * K) + qj] = r0[qi * K + qj];
        tmp[qi * (2 * K) + K + qj] = rm[qi * K + qj];
        tmp[(K + qi) * (2 * K) + qj] = rp[qi * K + qj];
        tmp[(K + qi) * (2 * K) + K + qj] = r0[qi * K + qj];
      }
      SYNCTHREADS();

      // R = hgT^T @ tmp @ hgT via two-pass axis contraction (see header
      // comment above get_rnlp_device for the mTxmq-derived verification of
      // this convention). Each pass reads one buffer and writes a different
      // one (tmp->t0, then t0->rmat).
      for (size_type idx = thread_id(); idx < 2 * K * 2 * K; idx += block_size()) {
        size_type qi = idx / (2 * K), qj = idx % (2 * K);
        T acc = T(0);
        for (size_type k = 0; k < 2 * K; ++k) acc += tmp[k * (2 * K) + qi] * hgT(k, qj);
        t0[idx] = acc;
      }
      SYNCTHREADS();
      for (size_type idx = thread_id(); idx < 2 * K * 2 * K; idx += block_size()) {
        size_type qi = idx / (2 * K), qj = idx % (2 * K);
        T acc = T(0);
        for (size_type k = 0; k < 2 * K; ++k) acc += t0[k * (2 * K) + qi] * hgT(k, qj);
        rmat[idx] = acc;
      }
      SYNCTHREADS();

      // S = R's pre-transpose top-left KxK block.
      for (size_type idx = thread_id(); idx < K * K; idx += block_size()) {
        size_type qi = idx / K, qj = idx % K;
        smat[idx] = rmat[qi * (2 * K) + qj];
      }
      SYNCTHREADS();

      // Transpose R (2Kx2K) and S (KxK) in place, matching convolutiondata.h
      // -- safe in place, see this function's header comment.
      for (size_type idx = thread_id(); idx < 2 * K * 2 * K; idx += block_size()) {
        size_type qi = idx / (2 * K), qj = idx % (2 * K);
        if (qi < qj) {
          T v = rmat[qi * (2 * K) + qj];
          rmat[qi * (2 * K) + qj] = rmat[qj * (2 * K) + qi];
          rmat[qj * (2 * K) + qi] = v;
        }
      }
      for (size_type idx = thread_id(); idx < K * K; idx += block_size()) {
        size_type qi = idx / K, qj = idx % K;
        if (qi < qj) {
          T v = smat[qi * K + qj];
          smat[qi * K + qj] = smat[qj * K + qi];
          smat[qj * K + qi] = v;
        }
      }
      SYNCTHREADS();

      // NSnormf needs R with its top-left KxK block zeroed; build that into
      // its own scratch region rather than mutating rmat (still needed below
      // for R_dst and Rnormf). Zeroing commutes with the transpose above
      // since that block maps to itself under it.
      for (size_type idx = thread_id(); idx < 2 * K * 2 * K; idx += block_size()) {
        size_type qi = idx / (2 * K), qj = idx % (2 * K);
        ns_scratch[idx] = (qi < K && qj < K) ? T(0) : rmat[idx];
      }
      SYNCTHREADS();

      T rnormf = normf(rmat, 2 * K * 2 * K);
      T snormf = normf(smat, K * K);
      T nsnormf = normf(ns_scratch, 2 * K * 2 * K);

      for (size_type idx = thread_id(); idx < 2 * K * 2 * K; idx += block_size())
        R_dst(idx / (2 * K), idx % (2 * K)) = rmat[idx];
      for (size_type idx = thread_id(); idx < K * K; idx += block_size())
        S_dst(idx / K, idx % K) = smat[idx];

      if (is_team_lead()) {
        // norms_dst order: Rnorm, Snorm, Rnormf, Snormf, NSnormf (see conv_mad.h's NormId).
        norms_dst[0] = sqrt(T(2 * K)) * rnormf; // Rnorm: conservative bound, not MADNESS's exact
        norms_dst[1] = sqrt(T(K)) * snormf;     // Snorm: SVD nuclear norm -- see header comment.
        norms_dst[2] = rnormf;
        norms_dst[3] = snormf;
        norms_dst[4] = nsnormf;
      }
      SYNCTHREADS();
    }

  } // namespace detail

  /// Per-(item, translation) scratch size (elements of T) that
  /// submit_generate_op1d_kernel expects via `workspace` -- see
  /// GaussianConvolutionOperator::submit_generation_kernel in conv_mad.h,
  /// which must allocate (and select()) workspace_size(K)*n_items*max_range_len
  /// (see submit_generate_op1d_kernel's comment for max_range_len).
  SCOPE size_type generate_op1d_workspace_size(size_type K) {
    return detail::op1d_workspace_offsets(K).total;
  }

  /**
   * One combined launch generating every (item, translation) pair implied by
   * `items` (device pointer, size n_items; each item's own [lmin, lmax] --
   * currently always the full level-wide range, see conv_mad.h's
   * collect_generation_items -- gives its number of translations) -- an
   * arbitrary flattened worklist, so this single kernel covers however many
   * (term, dimension, level, translation) entries a caller has collected,
   * whether that's one task's own multiple missing dimensions or (in a
   * future iteration) many sibling tasks' missing entries collected via a
   * ttg::device::coop() rendezvous -- see mra/misc/conv_mad.h.
   *
   * One block per (item, translation) pair, via a 2D grid: blockIdx.x
   * (grid-stride) selects the item, blockIdx.y (grid-stride) selects a
   * translation within THAT item's own [lmin, lmax] (items with a shorter
   * range than another simply leave the higher blockIdx.y values as no-ops
   * for themselves -- forward-compatible with the collect_generation_items
   * TODO about levels 0/1/2 needing fewer translations, without requiring
   * uniform ranges). Within a block, work is distributed cooperatively
   * across all its threads -- see generate_op1d_one's header comment.
   * Previously this was one block per item, looping over its whole
   * translation range SEQUENTIALLY inside the block (reusing one workspace
   * region, synchronized between iterations); this version gives each
   * (item, translation) pair its own block -- and hence lets independent
   * translations of the same item run concurrently on different SMs instead
   * of serialized on one -- at the cost of needing `max_range_len` times the
   * workspace (each pair needs its own disjoint scratch to run concurrently;
   * see `workspace`'s indexing below).
   *
   * `workspace` must have room for n_items * max_range_len *
   * generate_op1d_workspace_size(K) elements, laid out as a dense
   * [n_items][max_range_len] grid of per-pair regions (`max_range_len` is
   * the stride between items' regions, not necessarily any one item's own
   * range length -- see above); each (item, translation) pair uses its own
   * disjoint slice, so no synchronization is needed between blocks, only
   * within a single block's own generate_op1d_one call.
   */
  template <typename T, concepts::TensorView<3> ViewC, concepts::TensorView<2> ViewHgT,
            concepts::TensorView<2> ViewHgT2k, concepts::TensorView<6> ViewR, concepts::TensorView<6> ViewS,
            concepts::TensorView<5> ViewNorms>
  LAUNCH_BOUNDS(MAX_THREADS_PER_BLOCK)
  GLOBALSCOPE void generate_op1d_kernel(
      const GenerateOp1DItem<T>* items, size_type n_items, size_type max_range_len, size_type K,
      ViewC c, ViewHgT hgT,
      ViewHgT2k hgT2k_view, const T* quad_x, const T* quad_w, size_type npt,
      T* workspace, Translation l_offset, ViewR R, ViewS S, ViewNorms norms) {
    const size_type ws_size = generate_op1d_workspace_size(K);
    // put the hgT2k data into shared memory
    SHARED T hgT2k_shared[2 * MRA_MAX_K * 2 * MRA_MAX_K];
    ViewHgT2k hgT2k_shared_view(hgT2k_shared, 2 * K, 2 * K);
    hgT2k_shared_view = hgT2k_view;
    // load quad points and weights into shared memory
    SHARED T quad_x_shared[MRA_MAX_NPT];
    SHARED T quad_w_shared[MRA_MAX_NPT];
    for (size_type i = thread_id(); i < npt; i += block_size()) {
      quad_x_shared[i] = quad_x[i];
      quad_w_shared[i] = quad_w[i];
    }
    SYNCTHREADS();

    for (size_type item_idx = blockIdx.x; item_idx < n_items; item_idx += gridDim.x) {
      const auto& item = items[item_idx];
      const size_type range_len = (size_type)(item.lmax - item.lmin + 1);
      for (size_type y = blockIdx.y; y < range_len; y += gridDim.y) {
        const Translation lx = item.lmin + (Translation)y;
        T* item_workspace = workspace + (item_idx * max_range_len + y) * ws_size;
        detail::generate_op1d_one<T>(item, lx, K, c, hgT, hgT2k_shared_view, quad_x_shared, quad_w_shared, npt,
                                      item_workspace, l_offset, R, S, norms);
      }
    }
  }

  /**
   * Host-side launcher. `items` must already be resident on the current
   * device (n_items entries); `c`/`hgT`/`hgT2k`/`quad_x`/`quad_w` are the
   * shared (not per-item) tensors extracted once at operator construction
   * (see conv_mad.h). `max_range_len` is the workspace stride between items
   * (see generate_op1d_kernel's comment) -- conv_mad.h passes
   * MRA_OP1D_NUM_DISPLACEMENTS, matching how collect_generation_items()
   * currently always requests the full level-wide range. `workspace` must
   * be a device pointer with room for n_items * max_range_len *
   * generate_op1d_workspace_size(K) elements (see
   * GaussianConvolutionOperator::submit_generation_kernel/
   * make_generation_workspace in conv_mad.h, which allocate and select() it).
   * `R`/`S`/`norms` are the FULL, level-wide destination views
   * (detail::LevelOp1DTable's own tensors, already select()-ed by the
   * caller) -- every (item, translation) pair writes into its own (d, *, c,
   * i) slice of these, indexed by translation via `l_offset` (added to a
   * translation to get its index along the translation axis; conv_mad.h
   * passes MRA_OP1D_MAX_DISPLACEMENT, matching how the table was sized).
   * Thread block sized by K via the same max_thread_dims() helper
   * submit_convolution_kernel uses, since the per-(item, translation) work
   * is genuinely distributed across the block -- see generate_op1d_one's
   * header comment. Grid is 2D: x covers items, y covers `max_range_len`
   * (see generate_op1d_kernel's comment on why blocks beyond a shorter
   * item's own range are harmless no-ops).
   */
  template <typename T, concepts::TensorView<3> ViewC, concepts::TensorView<2> ViewHgT,
            concepts::TensorView<2> ViewHgT2k, concepts::TensorView<6> ViewR, concepts::TensorView<6> ViewS,
            concepts::TensorView<5> ViewNorms>
  void submit_generate_op1d_kernel(
      const GenerateOp1DItem<T>* items, size_type n_items, size_type max_range_len, size_type K,
      const ViewC& c, const ViewHgT& hgT,
      const ViewHgT2k& hgT2k, const T* quad_x, const T* quad_w, size_type npt,
      T* workspace, Translation l_offset, const ViewR& R, const ViewS& S, const ViewNorms& norms,
      ttg::device::Stream stream) {
    if (n_items == 0 || max_range_len == 0) return;
    Dim3 thread_dims = max_thread_dims(2 * K);
    Dim3 grid_dims((unsigned)n_items, (unsigned)max_range_len, 1);
    CALL_KERNEL((generate_op1d_kernel<T, ViewC, ViewHgT, ViewHgT2k, ViewR, ViewS, ViewNorms>), grid_dims, thread_dims, 0,
                stream, (items, n_items, max_range_len, K, c, hgT, hgT2k, quad_x, quad_w, npt, workspace, l_offset, R, S, norms));
    checkSubmit();
  }

  namespace detail {

    /**
     * Assembles ONE aggregate ConvolutionData's norms tensor entirely
     * on-device, from data that's already device-resident by the time this
     * runs: `norms1d` (the level table's, already select()-ed and, if this
     * round also generated the table, already filled by
     * generate_op1d_kernel -- no host round-trip needed) and `fac` (per
     * count-index/term, extracted once at operator construction, d-invariant
     * -- see conv_mad.h's m_shared_fac). Opnorm/Rank are NOT written here --
     * see assemble_op1d_opnorm_kernel below, which fills them in a separate
     * pass once every block here has written its MUnorm. One block per
     * (count-index c, term i); the work per block is tiny (NDIM*5 copies
     * plus two scalars), so only the team lead does anything -- no
     * cooperative distribution or SYNCTHREADS needed. Index order in the
     * last dimension of `norms` matches conv_mad.h's NormId exactly: Rnorm,
     * Snorm, Rnormf, Snormf, NSnormf, Fac, MUnorm, Opnorm, Rank.
     */
    template <typename T, Dimension NDIM, concepts::TensorView<5> ViewNorms1d, concepts::TensorView<2> ViewFac,
              concepts::TensorView<4> ViewNorms>
    GLOBALSCOPE void assemble_op1d_norms_kernel(
        size_type count, size_type rank, Level n,
        std::array<Translation, NDIM> lx, Translation l_offset,
        ViewNorms1d norms1d, ViewFac fac, ViewNorms norms) {
      const size_type idx = blockIdx.x;
      const size_type c = idx / rank;
      const size_type i = idx % rank;
      if (c >= count) return;
      if (!is_team_lead()) return;

      T nsnormf[NDIM];
      T snormf[NDIM];
      for (Dimension d = 0; d < NDIM; ++d) {
        const size_type l_idx = (size_type)(lx[d] + l_offset);
        auto src = norms1d(d, l_idx, c, i);
        norms(c, i, d, 0) = src[0]; // Rnorm
        norms(c, i, d, 1) = src[1]; // Snorm
        norms(c, i, d, 2) = src[2]; // Rnormf
        norms(c, i, d, 3) = src[3]; // Snormf
        norms(c, i, d, 4) = src[4]; // NSnormf
        nsnormf[d] = src[4];
        snormf[d] = src[3];
      }

      const T facv = fac(c, i);
      norms(c, i, 0, 5) = facv; // Fac

      // Ported from mra::GaussianConvolutionOperator::munorm2_ns (conv_mad.h):
      // computes the Frobenius norm of this term for the NS form, without
      // the factor included. Degrades gracefully to 0 for padding slots
      // (coeff==0 sentinel already zero-filled norms1d for those, so
      // nsnormf/snormf/facv are all 0 here too, and bb==0 zeroes prod).
      T prod = T(1), sum = T(0);
      for (Dimension d = 0; d < NDIM; ++d) {
        T a = nsnormf[d], b = snormf[d];
        T aa = a < b ? a : b;
        T bb = a < b ? b : a;
        prod *= bb;
        if (bb > T(0)) sum += (aa / bb);
      }
      if (n) prod *= sum;
      norms(c, i, 0, 6) = prod * fabs(facv); // MUnorm
    }

    /**
     * Assembles Opnorm/Rank for count-index c: Opnorm = sqrt(sum_i
     * MUnorm(c,i)^2) -- MADNESS's own SeparatedConvolution::getop_ns()
     * formula (see madness/mra/operator.h), computed here purely from the
     * MUnorm values assemble_op1d_norms_kernel just wrote, rather than via
     * SeparatedConvolution::norm(): that call goes through getop_ns()/
     * getmuop() to Convolution1D::nonstandard() on a cold ns_cache -- which
     * this device-generation path guarantees is always cold, since nothing
     * here ever warms MADNESS's own cache -- silently forcing exactly the
     * host-side R/S regeneration (plus an SVD, inside nonstandard()'s
     * ConvolutionData1D construction) that generating R/S on-device was
     * supposed to avoid. Unlike assemble_op1d_norms_kernel's tiny per-(c,i)
     * work, this genuinely benefits from being spread across the block: one
     * block per count-index c, cooperatively reducing over however many
     * terms (rank can be tens to hundreds). Must run on the SAME stream,
     * AFTER assemble_op1d_norms_kernel (see submit_assemble_op1d_norms_kernel/
     * submit_assemble_op1d_opnorm_kernel) -- CUDA stream ordering guarantees
     * every MUnorm is already written by the time this reads it, no
     * explicit wait() needed. `rank_tensor` is the per-count-index real
     * separated-expansion rank (conv_mad.h's m_shared_rank, extracted once
     * at operator construction -- unlike Opnorm this never needs a MADNESS
     * call per (level, displacement), since it depends only on the operator
     * itself, not on n or the displacement).
     */
    template <typename T, concepts::TensorView<4> ViewNorms, concepts::TensorView<1> ViewRank>
    GLOBALSCOPE void assemble_op1d_opnorm_kernel(size_type count, size_type rank, ViewNorms norms,
                                                  ViewRank rank_tensor) {
      const size_type c = blockIdx.x;
      if (c >= count) return;

      T s = T(0);
      for (size_type i = thread_id(); i < rank; i += block_size()) {
        T mu = norms(c, i, 0, 6); // MUnorm
        s += mu * mu;
      }
      SHARED T sum;
      reduce_block(s, &sum, std::min(rank, (size_type)block_size()));
      SYNCTHREADS();
      if (is_team_lead()) {
        norms(c, 0, 0, 7) = sqrt(sum);      // Opnorm
        norms(c, 0, 0, 8) = rank_tensor(c); // Rank
      }
    }

  } // namespace detail

  /**
   * Host-side launcher for detail::assemble_op1d_norms_kernel. `lx` is the
   * aggregate's own per-dimension translation (disp.translation()); `norms1d`
   * is the level table's full view (already select()-ed, and if this same
   * round also generated the table, already filled -- no wait() needed:
   * this kernel reads it on-device, unlike finish_op_assembly's host-side
   * equivalent for the MADNESS/host-cache path, which is what still needs
   * norms1d pulled back to host). One block per (count, rank) pair. Must be
   * followed by submit_assemble_op1d_opnorm_kernel (same stream) to fill in
   * Opnorm/Rank -- see that function's comment.
   */
  template <typename T, Dimension NDIM, concepts::TensorView<5> ViewNorms1d, concepts::TensorView<2> ViewFac,
            concepts::TensorView<4> ViewNorms>
  void submit_assemble_op1d_norms_kernel(
      size_type count, size_type rank, Level n, std::array<Translation, NDIM> lx, Translation l_offset,
      const ViewNorms1d& norms1d, const ViewFac& fac, const ViewNorms& norms,
      ttg::device::Stream stream) {
    if (count == 0 || rank == 0) return;
    Dim3 thread_dims{1, 1, 1};
    CALL_KERNEL((detail::assemble_op1d_norms_kernel<T, NDIM, ViewNorms1d, ViewFac, ViewNorms>),
                count * rank, thread_dims, 0, stream, (count, rank, n, lx, l_offset, norms1d, fac, norms));
    checkSubmit();
  }

  /**
   * Host-side launcher for detail::assemble_op1d_opnorm_kernel -- see its
   * comment. Call on the SAME stream, right after
   * submit_assemble_op1d_norms_kernel.
   */
  template <typename T, concepts::TensorView<4> ViewNorms, concepts::TensorView<1> ViewRank>
  void submit_assemble_op1d_opnorm_kernel(size_type count, size_type rank, const ViewNorms& norms,
                                           const ViewRank& rank_tensor, ttg::device::Stream stream) {
    if (count == 0 || rank == 0) return;
    Dim3 thread_dims(std::min((int)rank, (int)MAX_THREADS_PER_BLOCK), 1, 1);
    CALL_KERNEL((detail::assemble_op1d_opnorm_kernel<T, ViewNorms, ViewRank>), count, thread_dims, 0, stream,
                (count, rank, norms, rank_tensor));
    checkSubmit();
  }

  /**
   * Packs a host-side list of work items into a fresh ttg::Buffer, ready to
   * be select()-ed and passed to submit_generate_op1d_kernel. Kept as a free
   * function (not a coroutine) since only the caller's own device-task body
   * can co_await -- see conv_mad.h's GaussianConvolutionOperator header
   * comment.
   */
  template <typename T>
  ttg::Buffer<GenerateOp1DItem<T>> make_generate_op1d_items_buffer(
      const std::vector<GenerateOp1DItem<T>>& items) {
    auto ptr = std::shared_ptr<GenerateOp1DItem<T>[]>(new GenerateOp1DItem<T>[items.size()]);
    std::copy(items.begin(), items.end(), ptr.get());
    return ttg::Buffer<GenerateOp1DItem<T>>(std::move(ptr), items.size());
  }

} // namespace mra

#endif // MRA_KERNELS_GENERATE_OP1D_H
